### ISSUE TITLE
作者您好，请问做两次编码的好处是什么呢？

### ISSUE THREAD

**Issue by WilliamOChai** [ZhengPeng7/BiRefNet#105]
在birefnet.py的71行对原始分辨率的输入进行了第一次编码，在74行对降采样1/2的输入进行了第二次编码，然后特征分别cat了降采样后的特征，这样子做的好处是什么呢，是为了增加感受野吗？新人小白，对这段有一些疑问，请作者大大帮忙解答。

**Comment by ZhengPeng7** [comment]
可以去搜下图像金字塔. 主要这个任务中分辨率太高, 想让网络同时关注高分辨率的细节 和 低分辨率的语义.

**Comment by WilliamOChai** [comment]
好的，谢谢谢谢
