### ISSUE TITLE
Warning: Missing Node Types : When loading the graph, the following node types were not found:  BiRefNet

### ISSUE THREAD

**Issue by chamidusuraweera** [ZhengPeng7/BiRefNet#110]
Hi everyone,

I'm trying to install Clothing Factory V2 - Magic Clothing Workflow in ComfyUI

But in there showing **Warning: Missing Node Types  When loading the graph, the following node types were not found:  ReActorFaceSwap**

![Screenshot 2024-10-21 084719](https://github.com/user-attachments/assets/c28ab861-2daf-4899-bd41-fca44f159b9b)
---------------------------------------------------------------------------------------------------------------------------------------------------
**My workflow**

I trying to fix by these ways..

1. Clicking **Try Fix** Button, and Restart
2. Uninstall, and Restart
3. Install Via Git URL ([https://github.com/Gourieff/comfyui-reactor-node.git])

![Screenshot 2](https://github.com/user-attachments/assets/b09c1287-97ed-4311-8f16-d49b346d5bba)

But all the above 3 methods its showing **This action is not allowed with this security level configuration.**

![3](https://github.com/user-attachments/assets/4d369926-eb09-4d8c-a24c-9e792d20d4f0)

Magic Clothing Model in "D:\ComfyUI_windows_portable\ComfyUI\models\checkpoints" path.
![4](https://github.com/user-attachments/assets/73252b08-86a2-43ec-99f5-b34854f33fe8)

---------------------------------------------------------------------------------------------------------------------------------------------------

**Here are my system specifications:**

Laptop Model: Dell G5 5500
GPU: NVIDIA GeForce RTX 2070
Windows Version: 24H2
CUDA Version: 12.7

Current Versions:

Python: 3.12.0
pip: 23.2.1
xformers: 0.0.27

Browser - Google Chrome

---------------------------------------------------------------------------------------------------------------------------------------------------
**Console log
provided cmd logs from the moment Istarted UI to the momemt I got an error.**

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-21 10:19:11.980737
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI_windows_portable\ComfyUI
** Log path: D:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   2.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 16146 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 with Max-Q Design : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\__init__.py", line 3, in <module>
    from .BiRefNet_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\BiRefNet_node.py", line 7, in <module>
    from models.baseline import BiRefNet
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\baseline.py", line 11, in <module>
    from models.backbones.build_backbone import build_backbone
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\backbones\build_backbone.py", line 8, in <module>
    from utils import check_download_model
ImportError: cannot import name 'check_download_model' from 'utils' (D:\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet module for custom nodes: cannot import name 'check_download_model' from 'utils' (D:\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2775 [f9f9fafa] | Released on '2024-10-20'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-perturbed-attention
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mask-util
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.5 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-magic-clothing
   0.5 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.7 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.7 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet
   
---------------------------------------------------------------------------------------------------------------------------------------------------

**Same Issue with ReActorFaceSwap Node**

Has anyone experienced this issue and found a solution? Any help would be greatly appreciated!
Thank you!

**Comment by ZhengPeng7** [comment]
I'm not experienced at ComfyUI, but I hope someone can see this and give some suggestions.
But you can try some upgraded versions, such as [lldacing/ComfyUI_BiRefNet_ll](https://github.com/lldacing/ComfyUI_BiRefNet_ll) and [MoonHugo/ComfyUI-BiRefNet-Hugo](https://github.com/MoonHugo/ComfyUI-BiRefNet-Hugo), instead of the very first one. Many people met some strange problems and conflicts with other nodes when using that old one.

**Comment by unpezcado** [comment]
Hi @chamidusuraweera Did you manage to solve the problem? The same thing happens to me and I can't find a solution.

**Comment by chamidusuraweera** [comment]
> Hi @chamidusuraweera Did you manage to solve the problem? The same thing happens to me and I can't find a solution.

Hello @unpezcado. Sadly No!, Tried several times. and searching how to solve.

**Comment by ZhengPeng7** [comment]
Have you tried other newer BiRefNet nodes I mentioned above?
