### ISSUE TITLE
分割主体问题

### ISSUE THREAD

**Issue by PMPBinZhang** [ZhengPeng7/BiRefNet#111]
您好，可以指定目标分割吗？现在分割的标准是什么呢

**Comment by ZhengPeng7** [comment]
可以试试README里的`Box Guided Segmentation`的colab demo.

**Comment by PMPBinZhang** [comment]
好的，感谢您

**Comment by ZhengPeng7** [comment]
客气了. 对了, 刚看到, 后半句忘记回答了.... 标准总是根据训练数据来的. 比如现在的模型中, 用的数据集基本都是以显著的主体为目标, 所以自动分割的目标就也是这样的物体.

**Comment by PMPBinZhang** [comment]
好的。明白了。谢谢😁

| |
Wenwu Zhang
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Peng ***@***.***> |
| 发送日期 | 2024年10月25日 16:44 |
| 收件人 | ZhengPeng7/BiRefNet ***@***.***> |
| 抄送人 | PMPBinZhang ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ZhengPeng7/BiRefNet] 分割主体问题 (Issue #111) |

客气了. 对了, 刚看到, 后半句忘记回答了.... 标准总是根据训练数据来的. 比如现在的模型中, 用的数据集基本都是以显著的主体为目标, 所以自动分割的目标就也是这样的物体.
