### ISSUE TITLE
这个方法的 image.shape[-2]，没有接收image

### ISSUE THREAD

**Issue by hjj-lmx** [ZhengPeng7/BiRefNet#116]
def patches2image(patches, grid_h=2, grid_w=2, patch_ref=None, transformation='(b hg wg) c h w -> b c (hg h) (wg w)'):
    if patch_ref is not None:
        grid_h, grid_w = patch_ref.shape[-2] // image.shape[-2], patch_ref.shape[-1] // image.shape[-1]
    image = rearrange(patches, transformation, hg=grid_h, wg=grid_w)
    return image

**Comment by ZhengPeng7** [comment]
感谢指出, 我去修改一下, 这里的`image`应该换成`patches[0]`.
