### ISSUE TITLE
Inference for tiny model of BiRefNet

### ISSUE THREAD

**Issue by MK-1307** [ZhengPeng7/BiRefNet#117]
I'm getting the errors while loading the tiny version,
"size mismatch for bb.patch_embed.proj.weight: copying a param with shape torch.Size([96, 3, 4, 4]) from checkpoint, the shape in current model is torch.Size([192, 3, 4, 4])."

I'm getting these type lines a lot. can you guide how to resolve this issue.

"def load_model():
    birefnet = BiRefNet(bb_pretrained=False)
    state_dict = torch.load('./BiRefNet-general-bb_swin_v1_tiny-epoch_232.pth', map_location=device)
    state_dict = check_state_dict(state_dict)
    birefnet.load_state_dict(state_dict)
    birefnet.to(device)  # Change to 'cuda' if using a GPU
    birefnet.eval()
    return birefnet
"

**Comment by ZhengPeng7** [comment]
Thanks, I'll check about it toady.

**Comment by ZhengPeng7** [comment]
I checked it, but no problem occurred.
You can test the BiRefNet_lite by loading weights from the local file (what you did) in this temporary colab: https://colab.research.google.com/drive/1P1UVrV9YWiwlacGRV6A1X-IXHmo2n4ht?usp=sharing.
Tell me if you have any problems here.

**Comment by MK-1307** [comment]
i haven't changed the **bb** in **config.py** to **swin_v1_tiny**, i will do that now. Thanks for the response.
