### ISSUE TITLE
训练时等很久，一直没有出现打印loss等信息

### ISSUE THREAD

**Issue by zhenzi0322** [ZhengPeng7/BiRefNet#118]
![image](https://github.com/user-attachments/assets/92e01f22-ecf7-4087-9111-6c1cb360e22f)

请问一下：这种情况是不是正常的？还是在训练的？

**Comment by zhenzi0322** [comment]
![image](https://github.com/user-attachments/assets/b5bd7d0b-cfd5-4753-987c-4af16e10224f)

改成5了，等了很长时间还是没有见有一个打印数据出来，一直不打印loss信息出来，我也不清楚是不是正在正常训练中

**Comment by ZhengPeng7** [comment]
是什么GPU啊? 实在不行, 直接在`for`循环里的开头直接加个新的一行`print('batch_idx:', batch_idx)`?
https://github.com/ZhengPeng7/BiRefNet/blob/e3d2e13ecddbabd89ea90067f79f1836883f179a/train.py#L302

**Comment by zhenzi0322** [comment]
A100-PCIE-40GB

![image](https://github.com/user-attachments/assets/1bdd99ce-2fef-47bb-af12-6d8394b0398d)

**Comment by ZhengPeng7** [comment]
对了, 还有`config.py`里的`compile`可以先设为`False`, 这个会在开头耗费大量的时间进行编译. 但`compile`按理说会输出很多log内容的.

**Comment by zhenzi0322** [comment]
好的，这个之后尝试下。请教一下：针对`DIS5K`数据集训练，`train.py`中针对`epochs=120`，难道是训练`120`次迭代就能看到很好的效果了？

**Comment by zhenzi0322** [comment]
![image](https://github.com/user-attachments/assets/1d2c022d-9bc0-4c51-8806-46865a920fd3)

现在正常打印出来了，等了差不多四十分钟，正在训练了

**Comment by zhenzi0322** [comment]
> 不是, 需要500. 设置在`train.sh`里....

好的，谢谢了

**Comment by ZhengPeng7** [comment]
你检查一下是不是开了`compile`. 这个成功开启的话, 能够让training加速~30%.

**Comment by zhenzi0322** [comment]
好的，这个`compile=True`, 开了。在`config.py`中我只修改了`batch_size=2`, 其他选项采用默认的。因为`batch_size=4`会显存溢出。

![image](https://github.com/user-attachments/assets/162c2026-be92-47dd-8213-7fa4d2538f70)

**Comment by ZhengPeng7** [comment]
是的, 那就合理了, 属于程序正常行为.
