### ISSUE TITLE
Which model is the best choice for 2k-resolution images?

### ISSUE THREAD

**Issue by krahets** [ZhengPeng7/BiRefNet#123]
First of all, thanks for the amazing project!

I want to generate foreground masks for a human dataset with images (1920x1920 pixels). I noticed the newly released model BiRefNet_lite-2K is smaller than the main model BiRefNet. I'm wondering which one is the best choice for the 2K-res dataset.

- [BiRefNet_lite-2K](https://huggingface.co/ZhengPeng7/BiRefNet_lite-2K) + use original resolution.
- [BiRefNet](https://huggingface.co/ZhengPeng7/BiRefNet) + downscale the images to 1K.

**Comment by ZhengPeng7** [comment]
Overall, theoretically, in most metrics, [BiRefNet](https://huggingface.co/ZhengPeng7/BiRefNet) > [BiRefNet_lite-2K](https://huggingface.co/ZhengPeng7/BiRefNet_lite-2K) > [BiRefNet_lite](https://huggingface.co/ZhengPeng7/BiRefNet_lite).

But in practice, concerning the GPU cost efficiency, I recommend using the [BiRefNet_lite-2K](https://huggingface.co/ZhengPeng7/BiRefNet_lite-2K) if the image size is fixed as 2K (2560, 1440).

You'd better have some samples for a simple test by yourself -- it's very very easy to switch different versions of BiRefNet and do the fast inference in a batch using my [HF demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo).

**Comment by krahets** [comment]
Thank you for the guidance! This is an awesome demo that allows me to easily compare different models.

**Comment by krahets** [comment]
One more small question: if I use [BiRefNet](https://huggingface.co/ZhengPeng7/BiRefNet), which one do you recommend:
- Directly predict masks by inputting the 2K images into the model?
- Resize the images to (1024, 1024), predict the masks using the model, and then resize the masks back to the original image size?

**Comment by ZhengPeng7** [comment]
Use the [standard BiRefNet](https://huggingface.co/ZhengPeng7/BiRefNet) for general use.
