### ISSUE TITLE
边缘有什么办法能减弱点吗？

### ISSUE THREAD

**Issue by hjj-lmx** [ZhengPeng7/BiRefNet#124]
![企业微信截图_17315493784687](https://github.com/user-attachments/assets/472392a8-fce2-4ea5-89b9-00fe2ac4d065)

**Comment by ZhengPeng7** [comment]
用的是我的[demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo)吗? 或者colab的也都行. 其中有[refine_foreground](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo/blob/73527b185784dd312d6b7771622341ddba2ddb77/app.py#L145)这行吗? 他是用了[fast-foreground-estimation](https://github.com/Photoroom/fast-foreground-estimation), 对于这种白边 (红边也是) 有比较好的抑制效果.

**Comment by hjj-lmx** [comment]
> 用的是我的[demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo)吗? 或者colab的也都行. 其中有[refine_foreground](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo/blob/73527b185784dd312d6b7771622341ddba2ddb77/app.py#L145)这行吗? 他是用了[fast-foreground-estimation](https://github.com/Photoroom/fast-foreground-estimation), 对于这种白边 (红边也是) 有比较好的抑制效果.

我是用的BiRefNet_inference.ipynb中的代码改写的

**Comment by ZhengPeng7** [comment]
可以给下上面两张图加上`refine_foreground`的效果吗, 也可以供后续人参考, 多谢!

**Comment by pangxiaobin** [comment]
> 用的是我的[demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo)吗? 或者colab的也都行. 其中有[refine_foreground](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo/blob/73527b185784dd312d6b7771622341ddba2ddb77/app.py#L145)这行吗? 他是用了[fast-foreground-estimation](https://github.com/Photoroom/fast-foreground-estimation), 对于这种白边 (红边也是) 有比较好的抑制效果.

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/e134d30c-d679-4cb6-afc2-4fdf8bc7088c">
这个在线demo应该使用这个方法了吧，但是红边还是很明显

**Comment by ZhengPeng7** [comment]
很可能没有实现, 这个网站是我的几个学弟搞的, 因为搭建还是比较幸苦的, 我不怎么处理得过来.
直接用我上面说的我在HF spaces部署的demo 试试看.
