### ISSUE TITLE
Could someone provide to me a guide to do fine-tuning?

### ISSUE THREAD

**Issue by YarvixPA** [ZhengPeng7/BiRefNet#125]
Hello, I hope you’re doing well.

I’m interested in learning how to fine-tune BiRefNet. Although I’m not very knowledgeable about this topic, I’m eager to learn.

Could you please provide a begginer step-by-step guide :

- How to install
- How to prepare the dataset
- How to configure the training
- Other things?

I truly appreciate your time and assistance.

**Comment by ZhengPeng7** [comment]
Hi, I've already provided the [guideline of fine-tuning](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#pen-fine-tuning-on-custom-data) in the README...

And basic usage: https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#usage.

After following these guidelines, if you still have questions, feel free to tell me.

**Comment by YarvixPA** [comment]
Right, let me check

I have also made a node in ComfyUI that implements BiRefNet, BiRefNet Lite, BiRefNet Lite 2K and RMBG 2.0

I would like you to see it to see if it’s appropriate😅 I usually create nodes with the help of AI because I don’t know how to program but at the same time I’m there learning 😬

It is in this custom node:

https://github.com/YarvixPA/ComfyUI-NeuralMedia

I’m going to keep looking at the finetune guide😬😅

**Comment by ZhengPeng7** [comment]
So, you are new to programming? I can tell you about it in more detail:
1. How to install: [only two lines](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#environment-setup).
2. How to prepare the dataset: as given in [pre-requisites](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#pen-fine-tuning-on-custom-data) part of fine-tuning guideline or refer to [this reply](https://github.com/ZhengPeng7/BiRefNet/issues/43#issuecomment-2247198180) for a file tree structure.
3. How to configure the training: refer to the [fine-tuning guideline](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#pen-fine-tuning-on-custom-data) or [this reply](https://github.com/ZhengPeng7/BiRefNet/issues/86#issuecomment-2363682554).

Hope you enjoy programming!
