### ISSUE TITLE
混合精度训练

### ISSUE THREAD

**Issue by minushuang** [ZhengPeng7/BiRefNet#129]
您好 @ZhengPeng7 ，我使用了您更新的最新的关于混合精度更新的代码，训练过程中发现，1 epoch 的耗时相对非混合精度的耗时提高了不少，显存是降低了，请问训练耗时增加这个是正常的吗？您在使用混合精度训练时，是否会获得性能（耗时）的提升呢？

**Comment by minushuang** [comment]
看了下commit，对应更改的是dataloader部分，我pull下来测试了下，确实有提速，10%左右，您在使用accelerate时，获得性能提速大概多少呢？

**Comment by ZhengPeng7** [comment]
我这里测试是 和不用accelerate没差了, 基本一致.

**Comment by minushuang** [comment]
> 我这里测试是 和不用accelerate没差了, 基本一致.

也就是说accelerate实际上只是使显存降低了是吗，训练速度没有显著变化

**Comment by ZhengPeng7** [comment]
是的, 没错
