### ISSUE TITLE
birefnet.load_state_dict(state_dict)问题

### ISSUE THREAD

**Issue by Code-dogcreatior** [ZhengPeng7/BiRefNet#133]
我尝试使用本地调用但是在birefnet.load_state_dict(state_dict)这里报错：Traceback (most recent call last):
  File "d:\Image\BiRefNet\test.py", line 18, in <module>
    birefnet.load_state_dict(state_dict)
  File "D:\Anaconda\envs\matting\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BiRefNet:
        Missing key(s) in state_dict: "bb.layers.2.blocks.6.norm1.weight", "bb.layers.2.blocks.6.norm1.bias", "bb.layers.2.blocks.6.attn.relative_position_bias_table", "bb.layers.2.blocks.6.attn.relative_position_index", "bb.layers.2.blocks.6.attn.qkv.weight", "bb.layers.2.blocks.6.attn.qkv.bias", "bb.layers.2.blocks.6.attn.proj.weight", "bb.layers.2.blocks.6.attn.proj.bias", "bb.layers.2.blocks.6.norm2.weight", "bb.layers.2.blocks.6.norm2.bias", "bb.layers.2.blocks.6.mlp.fc1.weight", "bb.layers.2.blocks.6.mlp.fc1.bias", 后面还有很多都是这个层的数据我就不复制了。
看最后几行感觉是我调用2K是不是要修改input？       
例如后面是 size mismatch for decoder.gdt_convs_3.0.weight: copying a param with shape torch.Size([16, 384, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 768, 3, 3]).
        size mismatch for decoder.gdt_convs_2.0.weight: copying a param with shape torch.Size([16, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 384, 3, 3]).
我的调用代码是直接从jupyter中获取的，使用2K模型：
# # Option-3: Loading model and weights from local disk:
from utils import check_state_dict
from PIL import Image
import torch
from torchvision import transforms

import sys
sys.path.insert(0, "../")
from models.birefnet import BiRefNet

import os
from glob import glob
from image_proc import refine_foreground

birefnet = BiRefNet(bb_pretrained=False)
state_dict = torch.load('BiRefNet_lite-general-2K-epoch_232.pth', map_location='cpu', weights_only=True)
state_dict = check_state_dict(state_dict)
birefnet.load_state_dict(state_dict)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.set_float32_matmul_precision(['high', 'highest'][0])

birefnet.to(device)
birefnet.eval()
print('BiRefNet is ready to use.')

# Input Data
transform_image = transforms.Compose([
    transforms.Resize((1024, 1024)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

src_dir = '../images_todo'
image_paths = glob(os.path.join(src_dir, '*'))
dst_dir = '../predictions'
os.makedirs(dst_dir, exist_ok=True)
for image_path in image_paths:
    print('Processing {} ...'.format(image_path))
    image = Image.open(image_path)
    input_images = transform_image(image).unsqueeze(0).to(device)

    # Prediction
    with torch.no_grad():
        preds = birefnet(input_images)[-1].sigmoid().cpu()
    pred = preds[0].squeeze()

    # Show Results
    pred_pil = transforms.ToPILImage()(pred)
    pred_pil.resize(image.size).save(image_path.replace(src_dir, dst_dir))

    image_masked = refine_foreground(image, pred_pil)
    image_masked.putalpha(pred_pil.resize(image.size))

# Visualize the last sample:
# Scale proportionally with max length to 1024 for faster showing
scale_ratio = 1024 / max(image.size)
scaled_size = (int(image.size[0] * scale_ratio), int(image.size[1] * scale_ratio))

环境配置如下
（Package            Version
------------------ ------------
certifi            2024.8.30
charset-normalizer 3.4.0
colorama           0.4.6
einops             0.8.0
filelock           3.16.1
fsspec             2024.10.0
huggingface-hub    0.26.2
idna               3.10
imageio            2.36.0
Jinja2             3.1.4
kornia             0.7.4
kornia_rs          0.1.7
lazy_loader        0.4
MarkupSafe         3.0.2
mpmath             1.3.0
networkx           3.4.2
numpy              1.26.4
opencv-python      4.10.0.84
packaging          24.2
pillow             11.0.0
pip                24.2
prettytable        3.12.0
PyYAML             6.0.2
requests           2.32.3
safetensors        0.4.5
scikit-image       0.24.0
scipy              1.14.1
setuptools         75.1.0
sympy              1.13.3
tifffile           2024.9.20
timm               1.0.11
torch              2.0.1+cu118
torchvision        0.15.2+cu118
tqdm               4.67.1
typing_extensions  4.12.2
urllib3            2.2.3
wcwidth            0.2.13
wheel              0.44.0
）

**Comment by ZhengPeng7** [comment]
是指[BiRefNet_lite-2K](https://huggingface.co/ZhengPeng7/BiRefNet_lite-2K)? 顾名思义, 他和`BiRefNet_lite`一样, backbone是lite (swin_v1_tiny)的, 所以要确保`config.py`里的`bb`是这个, load参数才会正确兼容.

**Comment by ZhengPeng7** [comment]
默认的是标准版的`BiRefNet`, 如果是`BiRefNet_lite`, 要先修改`config.py`里的`bb`为对应的backbone.

**Comment by Code-dogcreatior** [comment]
ok了ok了 不过还有一个麻烦请教，在您所上传的release中，我留意到有很多类型的模型，其中我较为关注的是例如matting-portrait-general这三个大类别在实际的使用中能否方便举例实际使用场景呢？其他我注意到可能和数据集有关，但并未实测，不知道实际效果。

**Comment by ZhengPeng7** [comment]
matting的话, 就是透明成份比较多, 比如毛发边缘和玻璃透光.
portrait和general顾名思义, 就是人像和通用.
一般来讲就先试试general的, 通常效果都是最好的.

**Comment by Code-dogcreatior** [comment]
感谢
