### ISSUE TITLE
TypeError: BiRefNet.__init_subclass__() takes no keyword arguments问题

### ISSUE THREAD

**Issue by yangmaoda** [ZhengPeng7/BiRefNet#134]
运行推理程序时出现”Traceback (most recent call last):
  File "D:\PycharmProjects\BiRefNet-main\inference.py", line 9, in <module>
    from models.birefnet import BiRefNet, BiRefNetC2F
  File "D:\PycharmProjects\BiRefNet-main\models\birefnet.py", line 30, in <module>
    class BiRefNet(
TypeError: BiRefNet.__init_subclass__() takes no keyword arguments“
是我的运行库版本问题吗

**Comment by ZhengPeng7** [comment]
可以`pip install -U huggingface-hub`下看看还有没有这个问题哈.

**Comment by yangmaoda** [comment]
> 可以`pip install -U huggingface-hub`下看看还有没有这个问题哈.

更新后成功噜，谢谢作者大大
