### ISSUE TITLE
我现在尝试用BirefNet.safetensor进行扣像处理，发现有很多的weights，不知道weights应该怎么选取。

### ISSUE THREAD

**Issue by ZzMLvzZ-792998470** [ZhengPeng7/BiRefNet#135]

**Comment by ZhengPeng7** [comment]
如果没有特定场景需求, 就顾名思义, 用general.

**Comment by ZzMLvzZ-792998470** [comment]
> 如果没有特定场景需求, 就顾名思义, 用general.
![image](https://github.com/user-attachments/assets/4db58aa7-31ef-4a63-80b3-6a0f16aa7b70)
不好意思哈，没表达清楚，是这个weights的选取我不太清楚

**Comment by ZhengPeng7** [comment]
这个`weights`是backbone的weights, 如果你不需要训练的话, 那其实可以不用管这个的. 在创建时设下参数不调用就可以: `BiRefNet(bb_pretrained=False)`.

**Comment by ZzMLvzZ-792998470** [comment]
> 这个`weights`是backbone的weights, 如果你不需要训练的话, 那其实可以不用管这个的. 在创建时设下参数不调用就可以: `BiRefNet(bb_pretrained=False)`.

原来如此 感谢大佬！
