### ISSUE TITLE
Resume training error, RuntimeError: Error(s) in loading state_dict for BiRefNet:

### ISSUE THREAD

**Issue by efwfe** [ZhengPeng7/BiRefNet#137]
Hello
Use train.sh to fine tune.

Weight/cv: swin_tiny_patch4_window7_224_22kto1k_finetune.pth
Resume model: BiRefNet-DIS-bb_swin_v1_tiny-epoch_575.pth

Log below.
![Screenshot from 2024-11-30 19-46-34](https://github.com/user-attachments/assets/97b8a75c-2d22-4b19-8811-ee280afd74d6)

**Comment by ZhengPeng7** [comment]
This should be caused by setting the batch size to 1. You can refer to this previous issue: #100.
