### ISSUE TITLE
Fastest model?

### ISSUE THREAD

**Issue by antithing** [ZhengPeng7/BiRefNet#138]
Hi, and thanks for this amazing repo. I am looking to run an onnx model in real time (less than 30ms for inference).

All the models I see are 1024 resolution, and take a second or so to retunr the matte.

What is the fastest model? If I could run at 512x512, might I get to the speed that I want? 

Can I just change the dimensions here?

```
from torchvision.ops.deform_conv import DeformConv2d
import deform_conv2d_onnx_exporter

# deform_conv2d op登録
deform_conv2d_onnx_exporter.register_deform_conv2d_onnx_op()

def convert_to_onnx(net, file_name='output.onnx', input_shape=(512, 512), device='cpu'):
    input = torch.randn(1, 3, input_shape[0], input_shape[1]).to(device)

    input_layer_names = ['input_image']
    output_layer_names = ['temp1', 'temp2', 'temp3', 'output_image']

    torch.onnx.export(
        net,
        input,
        file_name,
        verbose=True,
        opset_version=16,
        input_names=input_layer_names,
        output_names=output_layer_names,
    )
     

convert_to_onnx(birefnet, 'birefnet_1024x1024.onnx', input_shape=(512, 512), device='cpu')
```

**Comment by ZhengPeng7** [comment]
[BiRefNet_lite](https://huggingface.co/ZhengPeng7/BiRefNet_lite) is the fastest one (same as `BiRefNet-general-bb_swin_v1_tiny-epoch_232` in GitHub release and google drive).

**Comment by antithing** [comment]
Thanks! This is still 1024x1024, right? Is there a 512x512 version?

**Comment by ZhengPeng7** [comment]
It's still for 1024x1024.... Running in 512x512 would surely be much faster (x4?), but the model is trained with data in 1024x1024. So, inferencing with a different resolution may cause some bad performance, but it is still good to run in some cases.

**Comment by antithing** [comment]
Thanks! So to use a lower resolution, I would export to onnx and pass the resolution, right? As in my first comment?

**Comment by ZhengPeng7** [comment]
Yeah. But the accuracy is not guaranteed... You can first use my [online demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo) to try it with lower resolutions.

**Comment by ZhengPeng7** [comment]
Hi, I trained a BiRefNet for general use with resolution==512x512😎. You can find the [weights](https://drive.google.com/file/d/1poOqXyJRHew3VEbU95sP_FBfCoBWxOXK/view?usp=drive_link) and [results](https://drive.google.com/drive/folders/1kx4xte6bI2YFPiF-HNaW_H9aB1r6E5sY?usp=drive_link) on my google drive.

Its performance is better than `BiRefNet_lite` even with a lower resolution (512x512 vs 1024x1024), which you can find also in the links above.

**Comment by antithing** [comment]
Thank you! I am having trouble converting this to onnx, would it be possible to upload the onnx model? Thanks again!

**Comment by antithing** [comment]
I mean the onnx for this new model: BiRefNet-general-resolution_512x512-fp16-epoch_216.pth

**Comment by ZhengPeng7** [comment]
Yeah, of course. That's also what I mean.

**Comment by antithing** [comment]
Ah thank you! I didn't see that yesterday. Can I ask for a 512 version of the portrait model as well when you have some time? Thanks again!

**Comment by ZhengPeng7** [comment]
Sure, but currently, the sponsored GPUs are used for another longer training. When I have free GPU resources again, I'll try to take training on it.
However, in this version, several portrait datasets were also used for training. So, you can first use it and show me the bad cases. I'll take a look into them to measure if a model trained on only portrait datasets would help.

**Comment by ZhengPeng7** [comment]
The above model was trained in 512x512. But if you only want to test the speed and don't care about the performance, you can surely export it with 256x256 resolution outputs. You can use [the given colab demo](https://colab.research.google.com/drive/1z6OruR52LOvDDpnp516F-N4EyPGrp5om#scrollTo=7lFgKfPS8Icy) for converting pth to onnx.

**Comment by antithing** [comment]
Got it. Thank you!

**Comment by antithing** [comment]
Running this 512 model in tensorrt with fp16 gives me a 20ms inference time! Perfect.  Thanks again for your help.

**Comment by alfausa1** [comment]
Hi @antithing,

Could you please provide more details on how you managed to run the 512 model in TensorRT? Specifically, I’d like to know:

1. How you set up the model for TensorRT.
2. Where the ONNX version of this model is available.

Thanks!
