### ISSUE TITLE
issues with the training Code

### ISSUE THREAD

**Issue by rishabh063** [ZhengPeng7/BiRefNet#14]
Hey was starting my training , 

I just noticed some issues with the code quality . 

like having self.sys_home_dir = '/root/autodl-tmp' or self.data_root_dir = os.path.join(self.sys_home_dir, 'datasets/dis')

these kind of things make it hard to quickly start the training and one had to just dig into the code find the issues

**Comment by ZhengPeng7** [comment]
Hi Rishabh, To be honest, that's kind of the first thing in everything in every project. I've made almost all of them in `config.py` with only one appearance instead of most other projects, where you need to modify this kind of thing in many places for the definition among many Python files.

**Comment by ZhengPeng7** [comment]
I'll further make up the config file to put these kinds of things at the beginning.
