### ISSUE TITLE
大佬，这个模型能在现有的代码中直接使用吗？

### ISSUE THREAD

**Issue by hjj-lmx** [ZhengPeng7/BiRefNet#153]
https://huggingface.co/briaai/RMBG-2.0

**Comment by ZhengPeng7** [comment]
应该是可以的, 因为他们就是直接拿去然后用他们私有数据训了下.

**Comment by hjj-lmx** [comment]
> 应该是可以的, 因为他们就是直接拿去然后用他们私有数据训了下.

试了一下，还没有244的效果好
