### ISSUE TITLE
Remove background for comic drawings

### ISSUE THREAD

**Issue by ynie** [ZhengPeng7/BiRefNet#17]
Hello, thank you for the great model. The model works great most of the time, but it seems to have trouble with some "easy images" like the one below.  The it and pants are getting erased.  Is that a known issue? Thank you!
![ComfyUI_temp_hslot_00001_](https://github.com/ZhengPeng7/BiRefNet/assets/394026/03a7daae-5b48-495e-be59-8befe9d7acf1)
![Output_temp_kiyby_00001_](https://github.com/ZhengPeng7/BiRefNet/assets/394026/7f41d018-d7ff-4ded-b2f5-b23792e4c1d8)

**Comment by ynie** [comment]
Here are the weights im using:

`BiRefNet-ep480.pth
pvt_v2_b2.pth
pvt_v2_b5.pth
swin_base_patch4_window12_384_22kto1k.pth
swin_large_patch4_window12_384_22kto1k.pth`

**Comment by ZhengPeng7** [comment]
The weights there were copied from my google-drive. You can download the latest weights from my google-drive as links given in my README (it should be DIS-ep580). It may be better.

But this problem still exists as I tested this image in my [online demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo). In my mind, I tried to get a high recall with relatively lower resolution input, and it worked for some improvement (it's still not perfect, but it is indeed an idea of ensembling to alleviate this problem). I've attached the results of your image in both 1024x1024 and 768x768.
![result_1024x1024](https://github.com/ZhengPeng7/BiRefNet/assets/25921713/b16e3953-26c1-4515-b8c7-1a09b5826e82)

![result_768x768](https://github.com/ZhengPeng7/BiRefNet/assets/25921713/24a57566-77bf-4717-8079-3204add56985)

Also glad to hear more from you about it.

**Comment by ynie** [comment]
Thank you for the response. Is the idea that I should always resize to 768 X 768 before sending it to BiRefNet?

**Comment by ynie** [comment]
Sorry I'm still confused on how to do this via code. However, I have another question, what makes it difficult to remove the background from this image? The background is pretty green-ish. I can try to modify the output image and make it work better for BiRefNet. Any pointers? Thanks!

**Comment by ZhengPeng7** [comment]
Hi, Ynie,

I guess the high contrast between the bright person and his clothes and the low contrast between the pants and background jointly lead to the unsatisfying result. Of course, models may learn better on this (but this is not guaranteed). For example, using my latest weights you can perfectly extract the tie (also low contrast with the background) which was not extracted well in the result you provided:
<img width="927" alt="截屏2024-04-19 12 07 09" src="https://github.com/ZhengPeng7/BiRefNet/assets/25921713/6d2c03aa-8aec-4604-8a11-568e63bbd316">

**Comment by ynie** [comment]
Got it. Thank you!
