### ISSUE TITLE
incorrect Paper link in the readme

### ISSUE THREAD

**Issue by rishabh063** [ZhengPeng7/BiRefNet#2]
![image](https://github.com/ZhengPeng7/BiRefNet/assets/55680979/2852aa17-d4eb-41df-9f95-2a653304d41f)

Paper link mentioned in the read me opens GCoNet+: A Stronger Group Collaborative Co-Salient Object Detector (https://arxiv.org/pdf/2205.15469.pdf). 

Kindly update with the it to the correct https://arxiv.org/pdf/2401.03407.pdf

**Comment by ZhengPeng7** [comment]
Thanks. I copied the README from my previous proj and forgot to update the first link😂... Thanks again!
