### ISSUE TITLE
Can you provide a script to inference a single image?

### ISSUE THREAD

**Issue by Yogurt2019** [ZhengPeng7/BiRefNet#20]
It's too hard for me to find the right weight and the right backbone & decoder & other things to load your provided pretrained weights. I just wanted to inference some images of mine T.T
So can you please provide a script to inference a single image? Thanks a lot!

**Comment by ZhengPeng7** [comment]
Have you taken a try at the colab demo I provided?
If so, and you still have trouble, plz reply to me here. I'll make it even easier.

**Comment by Yogurt2019** [comment]
> Have you taken a try at the colab demo I provided? If so, and you still have trouble, plz reply to me here. I'll make it even easier.

Yes, I've tried, it won't run due to the update of your code. For example, there's no models/baseline.py in your code.
Thanks a lot for your reply!
感激不尽！

**Comment by ZhengPeng7** [comment]
I'm so sorry for that... I updated some filenames including that, but forgot to update the colab at the same time. I just updated the colab. Could you try it again? If you still have some trouble, I'll try to further make it simpler.

**Comment by Yogurt2019** [comment]
It could run now, thanks a lot for your help!
十分感谢！

**Comment by ZhengPeng7** [comment]
In [another issue](https://github.com/ZhengPeng7/BiRefNet/issues/22#issuecomment-2094001527), Rishabh provided a colab demo for easier single image inference. You can use it now if still have that need: [easier single image inference on colab](https://colab.research.google.com/drive/14Dqg7oeBkFEtchaHLNpig2BcdkZEogba?usp=drive_link).

**Comment by Yogurt2019** [comment]
> In [another issue](https://github.com/ZhengPeng7/BiRefNet/issues/22#issuecomment-2094001527), Rishabh provided a colab demo for easier single image inference. You can use it now if still have that need: [easier single image inference on colab](https://colab.research.google.com/drive/14Dqg7oeBkFEtchaHLNpig2BcdkZEogba?usp=drive_link).

已经用上了，谢谢！
