### ISSUE TITLE
Performance of ASPP module and ONNX conversion feasibility

### ISSUE THREAD

**Issue by JunseokLee3** [ZhengPeng7/BiRefNet#29]
I'm truly grateful and amazed by your model. However, I have a question. As mentioned in this issue (https://github.com/ZhengPeng7/BiRefNet/issues/26), the deform_conv2d is not working well. 

According to the ONNX documentation, deform_conv2d seems to be supported from version 22 onwards.

So, my question is: In your code, there is a line that says 'config.dec_att == 'ASPP''. Do you know how well this ASPP module performs? I couldn't find any ablation or comparison experiments in the paper where something other than Deconv was used.
If the performance drop with ASPP is not significant, I would like to try converting the model to ONNX.

**Comment by ZhengPeng7** [comment]
It could be not too much degradation in performance. Those with `deform_conv2d` should work a little better, but I don't know how much it is. However, I still personally suggest keeping the `deform_conv2d`. If you have the computation resources, you can have a try on training it.

**Comment by JunseokLee3** [comment]
Thank you for the response. I will give it a try

**Comment by ZhengPeng7** [comment]
Hi, you can now find the ONNX files of all weights files in the GitHub release or the `ONNX` folder in the stuff folder on my GDrive. For more info, plz check the `ONNX conversion` part in the [model zoo section](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#model-zoo). You can find the inference codes in notebooks there.

Tell me if you encounter any further problems when using them :)
