### ISSUE TITLE
Missing supplementary material in the paper

### ISSUE THREAD

**Issue by rishabh063** [ZhengPeng7/BiRefNet#3]
I was not able to figure where are the supplementary material present in the paper  . The pink color indicates that it is clickable but thats not the case . The information is also neither  present at the end of the paper nor in the git repo

**Comment by ZhengPeng7** [comment]
You can find it here: [[**stuff**](https://drive.google.com/drive/u/0/folders/1s2Xe0cjq-2ctnJBR24563yMSCOu4CcxM)].

**Comment by rishabh063** [comment]
I can see a lot of zip files , Most of them are Datasets . 

I am looking for  "The full definition of each
individual loss can be found in the supplementary material." and 

"For a comprehensive evaluation, we employ the Smeasure [6] (Sm), max/mean/weighted F-measure [1](...), mean
absolute error (MAE), and relax HCE [31] (HCEγ) to evaluate performance. Detailed descriptions of these metrics
can be found in the supplementary material."

where can i find more information about these

**Comment by ZhengPeng7** [comment]
The citations are consistent with those in the main article, which you can refer to.
Or you can find the definitions from [IS-Net](https://github.com/xuebinqin/DIS).
