### ISSUE TITLE
Not getting the same quality as Hugging face demo

### ISSUE THREAD

**Issue by ds-jpg** [ZhengPeng7/BiRefNet#30]
Dear Author, 

Thank you for your amazing work.

I tried deploying and running your code in my local with the same requirements as mentioned in the hugging face repo and using the same model that is BiRefNet-massive-epoch_240.pth but still we get a different quality . 

We are using cuda : 12.3 and python 3.10. 

Can you please guide me what I am doing wrong so I can get the same quality as hugging face demo?

Thanks in advance.

**Comment by ZhengPeng7** [comment]
Hi, thanks a lot for your interest :)
You mean you got different results with the same weights (even lower quality)? That's a problem.
Could you use the `single_image_inference` colab to have a try and provide the images of them for me to look into the problem?
Thank you very much, looking forward to hearing from you.

**Comment by ZhengPeng7** [comment]
Hey, how is it going? I do care about the differences of using different versions of libs.

**Comment by ZhengPeng7** [comment]
Re-open it if you still have any trouble.
