### ISSUE TITLE
该如何添加新的自定义数据集和使用预训练模型

### ISSUE THREAD

**Issue by Mlegbder** [ZhengPeng7/BiRefNet#35]
刚学python不久, 看着数据集那块好像写死在代码里了

**Comment by ZhengPeng7** [comment]
Hi, 你可以先参考[之前的issue](https://github.com/ZhengPeng7/BiRefNet/issues/10#issuecomment-2026931570)里我回复的第三条. 应该是很容易使用自定义数据集的. 如果再有问题, 欢迎继续留言.

**Comment by Mlegbder** [comment]
> 您好，您可以先参考[之前我回复的问题](https://github.com/ZhengPeng7/BiRefNet/issues/10#issuecomment-2026931570)中的第三条。 应该是很容易使用自定义数据集的。 如果再有问题，欢迎留言继续。

好的,感谢您
