### ISSUE TITLE
Training Suggestion 

### ISSUE THREAD

**Issue by Kaustubh-cpu** [ZhengPeng7/BiRefNet#37]
@ZhengPeng7  

can you please suggest some detail explanation of how to run the training to only the DIS dataset .as your readme file contain very less information about training and inference

**Comment by ZhengPeng7** [comment]
You can refer to [this part](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#run) in README, that's very easy with only one command. Make sure the `task=DIS5K` in `config.py`.

Thanks for your suggestion. I'll emphasize them in README as they are important.

**Comment by ZhengPeng7** [comment]
Feel free to re-open this issue if you still have problems conducting the training and test.
