### ISSUE TITLE
AttributeError: type object 'BiRefNet' has no attribute 'from_pretrained'. After updating the repository, the inference script on colab cannot be used.

### ISSUE THREAD

**Issue by YUANMU227** [ZhengPeng7/BiRefNet#38]
I saw that you updated the repository code three days ago, and it seems that the nn.Module and PyTorchModelHubMixin modules were deleted. However, when using the single-graph inference script of colab, the corresponding function cannot be called. The error is as follows:
https://colab.research.google.com/drive/14Dqg7oeBkFEtchaHLNpig2BcdkZEogba?usp=drive_link
![image](https://github.com/user-attachments/assets/40dd41ab-509b-42d3-873f-e879269e1fde)

报错：
Traceback (most recent call last):
    model = BiRefNet.from_pretrained('zhengpeng7/birefnet')
AttributeError: type object 'BiRefNet' has no attribute 'from_pretrained'

**Comment by ZhengPeng7** [comment]
You mean that you want to load and run BiRefNet locally, but the from_pretrained method can not be recognized?

**Comment by ZhengPeng7** [comment]
![截屏2024-07-16 17 32 37](https://github.com/user-attachments/assets/30d85686-3937-4f5e-996b-573b93d3b304)
I tried it again, and everything was okay as above. Can you show me your codes?

**Comment by ZhengPeng7** [comment]
没事, 在这里就行. 当然可以用中文交流, 请随意哈.

你的环境是按照我给的安装的吗, 有可能是环境问题: [ref-1](https://github.com/THU-MIG/yolov10/issues/180).

再其次, 如果急用, 可以先把huggingface相关的那几行删掉 然后原生python本地load权重使用, 直接去掉是不影响使用的.

**Comment by ZhengPeng7** [comment]
代码 我看上去是没问题的, 当然得看你运行结果, 毕竟有其他因素影响.
`bb_pretrained=False`是因为, 这里是inference, 直接读取了整体weights, 那自然不需要先去加载backbone的权重, 而且如果加载的话你需要把对应的backbone权重文件放在本地, 那就非常麻烦. 所以为了inference时的简洁, 我添加了`bb_pretrained=False`这个参数.

**Comment by aiot-tech** [comment]
Update the huggingface-hub version is all you need

**Comment by ZhengPeng7** [comment]
> Update the huggingface-hub version is all you need

Yeah, I also met that problem by myself weeks ago. It's caused by the missing of 'huggingface-hub'.
