### ISSUE TITLE
The optimal image input size

### ISSUE THREAD

**Issue by ynie** [ZhengPeng7/BiRefNet#41]
Hello again, I want to know what would be the ideal image input size. My app allows users to take photo from their camera and the image files are usually pretty big. I would like to resize the image before sending it to the cloud. What is the ideal input resolution for BiRefNet? Here is the workflow I'm thinking:

1) User takes a large raw photo
2) Resize it to a certain resolution and upload to the GPU
3) GPU Process the image including BiRefNet and getting the segmentation mask
4) Client scale up the segmentation mask to match with the original image

Thank you!

**Comment by ZhengPeng7** [comment]
The current ideal input resolution for BiRefNet is **1024x1024**, which is the resolution used for training and can be found in the codes here and the demo on HF.

**Comment by ynie** [comment]
Awesome. Thank you!
