### ISSUE TITLE
Real world Example Feedbacks

### ISSUE THREAD

**Issue by ynie** [ZhengPeng7/BiRefNet#44]
Hey ZhengPeng, I would like to show you some examples where I think BiRefNet can improve on these real world photos. The algorithm currently works great, but I hope these feedback can make it much better. Thank you again for your hard work.

**Comment by ynie** [comment]
Example:
![HBY-32380616 (8)](https://github.com/user-attachments/assets/92630e0d-d955-4a72-8da6-095e21cd7a62)

General Use Heavy
![e12a028733ae41039ba8fe5cf24764b3_5ac94f4aaee141ba997bda03c5fdad21](https://github.com/user-attachments/assets/5823450f-0134-4c6f-8c7a-ae2955116879)

Photoroom iOS
![Photoroom_20240725_080107 2](https://github.com/user-attachments/assets/c5a6e1fb-f290-49e2-b68e-04d3f51f09db)

**Comment by ynie** [comment]
![b98310a3818b65b040a1cb78b6df0195_2000x](https://github.com/user-attachments/assets/9cf1cc73-77d2-453a-8c3b-f725428da0f2)

General Use Heavy:
![f2b48965c74f4fd8be24886121d73364_43f4a79478a64dfc815d1eca94412526](https://github.com/user-attachments/assets/5edaf551-c28c-4f53-9bc0-9aa5b82a6836)

Photoroom on iOS:
![Photoroom_20240724_180903](https://github.com/user-attachments/assets/51e88636-44b6-45e8-8bd5-f2b07fea8f28)

**Comment by ZhengPeng7** [comment]
Wow, thanks. I appreciate it! Improvements need to be made to the contour areas, where the predicted values seem unconfident, neither 0 nor 1. I will look deep into the reason for it. Again, many thanks :)

**Comment by ynie** [comment]
no problem. I will keep this issue up to date with more issues I find.

**Comment by ZhengPeng7** [comment]
Sure, I would love to see more typical samples, but I also hope it doesn't cost you too much time.
BTW do you know if there are some open projects for subject extraction in the Photoroom app? I found this [ICIP 2021 work](https://github.com/Photoroom/fast-foreground-estimation) from them, of which codes seem incomplete though.

I can do anything except their private datasets to improve the quality of BiRefNet.

**Comment by ynie** [comment]
Not that I know of. Do you think this is a dataset issue?

**Comment by ynie** [comment]
Hey @ZhengPeng7 , I'm trying to send out a patch for the comfyUI node, which weight should I use for the examples above?
<img width="832" alt="image" src="https://github.com/user-attachments/assets/b9771e4a-5107-4464-abf6-c6ad02acc074">

Or which one is the general use heavy on Fal?

Thanks!

**Comment by ZhengPeng7** [comment]
The largest version for general use is currently the best one for images in the wild (the first line).

**Comment by ynie** [comment]
Hello @ZhengPeng7, just check in to see if what can I help with the basket example above. Please let me know what I can help. If you are actively working on it, do you have an ETA? Thank you so much.

**Comment by ZhengPeng7** [comment]
Hi, ynie, there were some mistakes in the previous training for this kind of task.
Dichotomous image segmentation is different from the image matting task (samples here) -- GT values are in 0 or 1 vs in 0 ~ 1. That's why the segmentation on the hairs of your cute dog is not good enough. I want to use more matting data and increase the weights of L1 loss instead of only BCE+IoU which are both used for DIS task.
But the white boundary of the predicted results is still solved... In the latest version, results are better but that bad phenomenon still exists, I'm still thinking about it. InSPyReNet seems very good on this regions, I'm trying to learn things from it.
<img width="1483" alt="截屏2024-08-07 11 19 47" src="https://github.com/user-attachments/assets/d62d818b-2c70-4238-a2c0-5aefdb13b9e5">

**Comment by ynie** [comment]
Hey Zhengpeng, thank you so much for the information. Will that improve the basket example above?

<img width="380" alt="image" src="https://github.com/user-attachments/assets/f43c0c23-c63f-4a7b-bee6-8c848801ad3a">

**Comment by ynie** [comment]
Here are two more examples:

Example 1:

Original:
![3080_R - 2000 x 1800 - 220dpi](https://github.com/user-attachments/assets/e139f62c-522e-4447-8fe6-32fa4e6d55da)

Photoroom:
![Photoroom_20240806_211020](https://github.com/user-attachments/assets/d168a317-6e6f-4d4d-ad01-b6cce85183d7)

General Use Heavy:
![Landscape 2](https://github.com/user-attachments/assets/395bf586-9340-4fcf-8e2a-ad63474f1e1d)


Example 2:

Original:
![1141_TS - 1500x1400 - 180dpi](https://github.com/user-attachments/assets/3d2cada8-0975-4f09-9ae5-6b33993a896d)

Photoroom:
![Photoroom_20240806_210834](https://github.com/user-attachments/assets/07c74041-0c8e-4c2f-9609-77415130881a)

General Use Heavy:
![Landscape 3](https://github.com/user-attachments/assets/0c1692ea-fba3-4406-bc29-1a012ddca151)
