### ISSUE TITLE
Question: training time for different models

### ISSUE THREAD

**Issue by schirrmacher** [ZhengPeng7/BiRefNet#46]
Do you have an overview how long you trained the models with different GPUs?

I am now training on a single NVIDIA GPU (4090) with the small backbone (swin_v1_t).

```
2024-07-28 09:08:01,653 INFO Epoch[1/150] Iter[0/5003]. Training Losses, loss_pix: 131.010
2024-07-28 09:20:59,744 INFO Epoch[1/150] Iter[20/5003]. Training Losses, loss_pix: 119.126
2024-07-28 09:31:38,230 INFO Epoch[1/150] Iter[40/5003]. Training Losses, loss_pix: 101.708
```
I think finishing the training might take (5000 / 20 * 10) = 2500 minutes for one epoch with my setup.
So maybe with consumer GPUs this is too compute heavy. Or are there any optimizations?

**Comment by ZhengPeng7** [comment]
Wow,  That's really huge time cost and iteration number in your case. I checked the 'General' (portraits data is added compared with the previous 'general') dataset setting in my training log, which would only take 26s for 20 / 1596 iterations on A100-80G x8 (batchsize=4, backbone=SwinL). Each epoch training takes ~35 min here and I made it trained for 250 epochs.

**Comment by schirrmacher** [comment]
Thanks for the insights, so I came to the following conclusion:

The model was trained on 8 x A100-80G, which require 35min for one epoch 
⇒ 3,64 days (150 epochs)
⇒ $14.32 / hr (AWS costs) * 87,36 hours 
⇒ 1.250 $

**Comment by ZhengPeng7** [comment]
Yeah, but that's for the general model, which is strongest for general use with much much more training data.

To obtain the model trained on DIS5K, of which the results are shown in the original paper, epoch epoch is less than 1.5 min. The model obtained in this case is already very good for daily use.
I also have the 4090, I will test the cost of training on it.

**Comment by schirrmacher** [comment]
Amazing thanks for your help. If I have new insights I will let you know.

**Comment by ZhengPeng7** [comment]
Hi, Mavin. I tried the training on DIS5K with BiRefNet with `bb=SwinT, batchsize=3` to occupy 22.3GB GPU memory. `compile` in `config.py` should be kept as `True`, otherwise, the training will slow down for ~20%.
Numerically, the training time of one epoch on DIS5K = `1s * 1000iter`, which may be kind of acceptable on one 4090.
<img width="468" alt="截屏2024-07-28 19 43 46" src="https://github.com/user-attachments/assets/d9388e6b-b4f3-440a-8230-233390eb7653">

**Comment by schirrmacher** [comment]
I will try it out! Incredibly good support, I appreciate this!

**Comment by minushuang** [comment]
> Wow, That's really huge time cost and iteration number in your case. I checked the 'General' (portraits data is added compared with the previous 'general') dataset setting in my training log, which would only take 26s for 20 / 1596 iterations on A100-80G x8 (batchsize=4, backbone=SwinL). Each epoch training takes ~35 min here and I made it trained for 250 epochs.



> Wow, That's really huge time cost and iteration number in your case. I checked the 'General' (portraits data is added compared with the previous 'general') dataset setting in my training log, which would only take 26s for 20 / 1596 iterations on A100-80G x8 (batchsize=4, backbone=SwinL). Each epoch training takes ~35 min here and I made it trained for 250 epochs.

hi @ZhengPeng7  how many images in general task you trained the model?

**Comment by minushuang** [comment]
> hi @ZhengPeng7 how many images you used for the general task ?

that's 1596 * 4 * 8 = 51072 imags

**Comment by ZhengPeng7** [comment]
> hi @ZhengPeng7 how many images you used for the general task ?

It's about 51,793 images in the current version, but may increase in future versions :)
