### ISSUE TITLE
Custom dataset fine-tuning

### ISSUE THREAD

**Issue by htaoruan** [ZhengPeng7/BiRefNet#49]
Great work, I'm trying to fine tune a DIS for other categories such as hair, changes were made in dataset.py to make sure the data loads without problems, and would like to ask which model is better to base the fine tuning on, and is the fine tuning setup tested below? --resume ... /weights/BiRefNet-general-epoch_244.pth Anything to note?

**Comment by ZhengPeng7** [comment]
What do you mean by `other categories`? No specified are required in the existing training.

Currently, I have not conducted experiments on which weights are better for fine-tuning... But that 'general one' is the most likely to work best.

And about the hair, which is a relatively special thing here -- do you want to do the matting task (labels are in 0~1) or dichotomous segmentation (labels are in 0 or 1)? If it's in the former condition, I would recommend also trying the weights for the portrait segmentation.

**Comment by htaoruan** [comment]
Thanks for your reply, would like to confirm that the fine-tuning based on BiRefNet-portrait-epoch_145.pth only requires modifying the resume parameter in mutil-gpu train right?

**Comment by ZhengPeng7** [comment]
You may also need to turn off the IoU fine-tuning in `config.py`, if your data is on matting.

**Comment by ZhengPeng7** [comment]
Feel free to re-open it if you still have questions.
