### ISSUE TITLE
there not exists dataset files in the google drive link.

### ISSUE THREAD

**Issue by vstar37** [ZhengPeng7/BiRefNet#5]
"DIS, COD, HRSOD"

**Comment by ZhengPeng7** [comment]
I re-organize the storage logic of these datasets in my google-drive.
I'm still upgrading several points to make the transfer between different tasks (DIS / COD / HRSOD) even more smooth with less storage requirement for experiments, which I will update in the README later.
But you can first find all the well-arranged datasets here: [DIS](https://drive.google.com/drive/u/0/folders/1hZW6tAGPJwo9mPS7qGGGdpxuvuXiyoMJ) / [COD](https://drive.google.com/drive/u/0/folders/1EyHmKWsXfaCR9O0BiZEc3roZbRcs4ECO) / [HRSOD](https://drive.google.com/drive/u/0/folders/18_hAE3QM4cwAzEAKXuSNtKjmgFXTQXZN). Feel free to download the combined xx_[TR/TE]sets, which should contain all the data you need. Or go into the single ones to download them one by one.
