### ISSUE TITLE
Feature: Onnx Export

### ISSUE THREAD

**Issue by schirrmacher** [ZhengPeng7/BiRefNet#50]
Do you plan to build an Onnx export? I like deploying models with Onnx to reduce dependencies and use the model in C++.

**Comment by ZhengPeng7** [comment]
Hi, Marvin, some others wanted it ([issue-1](https://github.com/ZhengPeng7/BiRefNet/issues/29#issue-2358963492), [issue-2](https://github.com/ZhengPeng7/BiRefNet/issues/26)).
But I'm new to deployment-related things and tried some easy tutorials on it, which failed though. So, this was suspended...

I'll give it another try when I have enough free time.

**Comment by antithing** [comment]
Watching, onnx in c++ would be amazing!

**Comment by ZhengPeng7** [comment]
Hi, you can find the ONNX files of all weights files in the GitHub release or the `ONNX` folder in the stuff folder on my GDrive. For more info, plz check the `ONNX conversion` part in the [model zoo section](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#model-zoo). You can find the inference codes in notebooks there.

Tell me if you encounter any further problems when using them :)

**Comment by antithing** [comment]
Thanks! Any tips on running with c++ instead of python?
Also, do I need to adjust any workflow to use on video files?

**Comment by ZhengPeng7** [comment]
Sorry, I'm not familiar with the inference in C++. About the video, it's easy to make the prediction on each frame and combine them into a video.

**Comment by schirrmacher** [comment]
Amazing! Thanks for the incredibly good support! ONNX helps a lot deploying the model in various contexts without requiring the Python data structures...

**Comment by schirrmacher** [comment]
@antithing I will publish the code here, I will integrate the model to my private C++ project. Will update you.

**Comment by ZhengPeng7** [comment]
Great work, @schirrmacher! You are welcome. I'm glad to do something if it can help.

**Comment by antithing** [comment]
@schirrmacher did you manage to run inference in c++?
