### ISSUE TITLE
Model weights when trained on HQ-Seg44k dataset

### ISSUE THREAD

**Issue by chrismaltais** [ZhengPeng7/BiRefNet#51]
Hey there!

[Segment Anything in High Quality (SAM-HQ)](https://github.com/SysCV/sam-hq) model released a dataset called HQ-Seg44k, which can be found [here](https://huggingface.co/sam-hq-team/sam-hq-training/tree/main/data). It includes the DIS5K dataset, but also other data that might be worthwhile to train on.

We seem to be on a roll of releasing different model weights for different practical applications, I'd be curious to see how including this new dataset in the **general use** model with the **swin_v1_large** backbone could affect model quality.

Kind of like what has been done by adding a dataset [here](https://github.com/ZhengPeng7/BiRefNet/commit/b74a71964896f20bfa672f81dba1db95ed4f6d8f)

**Comment by ZhengPeng7** [comment]
Hey, Chris, thanks for your suggestion! I've downloaded them to have a check, and they seem to be good to put into training
👍. But currently, the GPU support from Fal might be going to be closed (they have offered me so many GPU resources for months, and I really appreciate them). Therefore, I might not have that many computation resources to conduct this kind of massive training again. But I've kept them and your suggestion, which may work in the future.
