### ISSUE TITLE
training datset set 

### ISSUE THREAD

**Issue by yuanyang1991** [ZhengPeng7/BiRefNet#52]
Hello, the BirefNet work is excellent. I would like to know what the training set TR-humans used for training the general model (https://drive.google.com/file/d/1_IfUnu8Fpfn-nerB89FzdNXQ7zk6FKxc/view) is. Is there a related link available?

**Comment by ZhengPeng7** [comment]
Hi, [this](https://huggingface.co/datasets/schirrmacher/humans) is a high-quality synthesized human segmentation data made by @schirrmacher.
I also denoted its source in the [model zoo](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#model-zoo) (That's missed in the general use model; I'll also add links there).

**Comment by yuanyang1991** [comment]
Thank you very much for your reply. Birefnet is awesome.
