### ISSUE TITLE
inquiry about the convneck in ViTMatte

### ISSUE THREAD

**Issue by lucasgblu** [ZhengPeng7/BiRefNet#57]
First, congrats on this amazing job to push the boundary of image matting forward!

I took some time to read your paper along with the source code in the repo. As in the config, the backbone is swin_v1_l (I tried to run the colab code and did print the config to make sure what the backbone is), but I can not find the code for convneck as it presented in the paper. 

where can I find the convneck if I did not miss it in the code? Or is it dismissed in the real implementation?

congrats again!

**Comment by ZhengPeng7** [comment]
What do you by the `convneck`? I didn't find it in my paper. Weights with all different backbones are provided in the model zoo and the GDrive folder. ConvNets were also not used as the backbone in the original paper, and the implementation still has some problems ([issue before](https://github.com/ZhengPeng7/BiRefNet/issues/19)). I currently don't have time to validate it, but may fix it in the future.

**Comment by lucasgblu** [comment]
oh! sorry! my bad, I took wrong paper...

**Comment by ZhengPeng7** [comment]
Aha, no worry. I was also confused by why you talk about ViTMatte in the title.
