### ISSUE TITLE
So many models 

### ISSUE THREAD

**Issue by rishabh063** [ZhengPeng7/BiRefNet#58]
Hey @ZhengPeng7  I have been busy not been able to keep up with your progress 

I see many models on the drive ( stuff ) 

which is the best ones these days ?

Are you training even better one ?

Any comparison with closed source model now

**Comment by ZhengPeng7** [comment]
Hi, @rishabh063 , you can see the [GitHub release](https://github.com/ZhengPeng7/BiRefNet/releases/tag/v1) and my [Hugging Face models ](https://huggingface.co/ZhengPeng7) for those for practical use. Practically, you can directly use the one for general use, which is always maintained and updated on https://huggingface.co/ZhengPeng7/BiRefNet.

**Comment by ZhengPeng7** [comment]
I didn't have time to do the comparison with closed models, but some others did it. However, there are only cases not a comprehensive one.

**Comment by cyy-1234** [comment]
Hi,Peng,I would like to ask among the many versions, which one is better at segmenting real pictures with more obvious subjects. I look forward to your reply.
![image](https://github.com/user-attachments/assets/bbb8e277-9998-4edf-8774-960c732a7e57)

**Comment by ZhengPeng7** [comment]
`BiRefNet-general-epoch_244.pth` should be the best one for you.
And, of course, you can go to [HF demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo) to have a try online with different weights on some of your samples.

> Hi,Peng,I would like to ask among the many versions, which one is better at segmenting real pictures with more obvious subjects. I look forward to your reply. ![image](https://private-user-images.githubusercontent.com/59501159/359814687-bbb8e277-9998-4edf-8774-960c732a7e57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzc3NjksIm5iZiI6MTcyNDIzNzQ2OSwicGF0aCI6Ii81OTUwMTE1OS8zNTk4MTQ2ODctYmJiOGUyNzctOTk5OC00ZWRmLTg3NzQtOTYwYzczMmE3ZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEwNTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMDY1ZmEzZTA2NDc1NDY2MzZlYjVkOGE3YzQ0NzRiMGYwNTI2ZmIxZjcxYmVjY2RjZjBiZDdiYjhlMGQ5MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XXI53k0vaqOr6cGxgF3tGFwit4NiIgmPKZFXvv1AkHI)

**Comment by cyy-1234** [comment]
Hi，I used your excellent model（BiRefNet-general-epoch_244.pth），First of all, I think this model is very excellent，And believe that the future will be even better.
 and found that there are some segmentation problems in actual pictures, 
1. Mirror problem 
![image](https://github.com/user-attachments/assets/04b613ea-6664-4270-84ab-6fb6f180855d)
![image](https://github.com/user-attachments/assets/c2ce3fd5-ac48-4c9f-b63e-8857e6d65717)
![image](https://github.com/user-attachments/assets/188b6f25-6b8a-47b7-8d0e-05d5df3149d2)
2. Transparency problem 
![image](https://github.com/user-attachments/assets/ccac427b-a5f2-4601-94f3-8bc5d0f7bbe4)
![image](https://github.com/user-attachments/assets/9cab924e-d3b5-49ef-9a15-a661d9d96efb)
3. Hair problem (this is difficult)
![image](https://github.com/user-attachments/assets/69671430-5667-42f0-9c36-cfa3a398bdfa)
4、At the same time, sometimes I feel like there are white edges（Appears mostly on white background）
![image](https://github.com/user-attachments/assets/0f236b68-b425-4650-8b14-0ebd8c31ba62)

**Comment by cyy-1234** [comment]
Hi，Peng，I have tried many times and found that when the model is mounted on a plate, it is easy to miss the points on the plate. This phenomenon is very high. I don’t know if it is a problem.
![image](https://github.com/user-attachments/assets/cb17f589-48cf-4161-abd6-9ac24b612062)
![image](https://github.com/user-attachments/assets/f4891b4d-7a7b-4948-8656-5fdcf4bd67a5)
![image](https://github.com/user-attachments/assets/83dcc6af-024c-479e-9327-0af574f62350)

**Comment by ZhengPeng7** [comment]
Hi, cyy, that's caused by that the subject in the image seems to be the fruit/food, instead of the plate, which is recognized as the background. Since it's automatic subject extraction, this phenomenon is hard to avoid (it's correct).

Even so, I think you may be able to obtain the results you want through some tricks. For example, you can try with the box-guided segmentation colab -- add some background surroundings to make the plate and things on it look like a whole, then give a box surround the plate.

**Comment by ZhengPeng7** [comment]
I tried it by myself, it's currently impossible to include things that are not subject. It may need prompts (points/box) as what's used in SAM.

**Comment by ZhengPeng7** [comment]
> Hi，Peng，I have tried many times and found that when the model is mounted on a plate, it is easy to miss the points on the plate. This phenomenon is very high. I don’t know if it is a problem. ![image](https://private-user-images.githubusercontent.com/59501159/360847869-f4891b4d-7a7b-4948-8656-5fdcf4bd67a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjQyNjAsIm5iZiI6MTcyNDQyMzk2MCwicGF0aCI6Ii81OTUwMTE1OS8zNjA4NDc4NjktZjQ4OTFiNGQtN2E3Yi00OTQ4LTg2NTYtNWZkY2Y0YmQ2N2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0MzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMDMwMjYwNThiZDJhYTJhYmJlYzFmN2IyNTEzZGQzOWU2ODQ1ZjkzYTM2NGNhOWRkNDM1MDBkMGZiMDJlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fAxEnpZfns_FxFeSp5EG2iRPKDc9pYzEgKob3OHxmZA) ![image](https://private-user-images.githubusercontent.com/59501159/360856171-83dcc6af-024c-479e-9327-0af574f62350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjQyNjAsIm5iZiI6MTcyNDQyMzk2MCwicGF0aCI6Ii81OTUwMTE1OS8zNjA4NTYxNzEtODNkY2M2YWYtMDI0Yy00NzllLTkzMjctMGFmNTc0ZjYyMzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0MzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MzVmMTllODNiMzg2MmFkODU5NzU2NGNlMDY1NjA4ZjQ5M2MzMWE4YTQwODY0Zjc5MTkxNDlkOWEyYzQxYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9t2pft070sNRZlVAq3oNEqM0CL5Vi-ltQkJgWT5jdtc)

Hi, cyy, I surprisingly found that model trained on DIS5K only seems better on these cases (that's caused by how the labels are made in the datasets), you can directly use this model: https://huggingface.co/ZhengPeng7/BiRefNet-DIS5K-TR_TEs. Here are the results of your cases above (I downloaded your screenshot and did a crop).

![截屏2024-08-23 22 42 24](https://github.com/user-attachments/assets/bf96f32d-21f5-4d8a-83ee-273d48997383)
![截屏2024-08-23 22 45 32](https://github.com/user-attachments/assets/e87934ab-515e-42e9-affd-d9f3406ecf6b)

**Comment by cyy-1234** [comment]
wow,Awesome, I will try the model you recommended. @ZhengPeng7

**Comment by RaySteve312** [comment]
你俩为啥不直接中文说啊。。。

**Comment by hjj-lmx** [comment]
> ：[https](https://huggingface.co/ZhengPeng7/BiRefNet-DIS5K-TR_TEs) ://huggingface.co/ZhengPeng7/BiRefNet-DIS5K-TR_TEs

这个有个.pth的吗？好像没有看到

**Comment by hjj-lmx** [comment]
> Hi，Peng，我试了很多次发现模型装在板上的时候，很容易漏掉板上的点，这个现象出现得非常多，不知道是不是有问题。 ![图像](https://private-user-images.githubusercontent.com/59501159/360847869-f4891b4d-7a7b-4948-8656-5fdcf4bd67a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDc4ODQsIm5iZiI6MTczNTIwNzU4NCwicGF0aCI6Ii81OTUwMTE1OS8zNjA4NDc4NjktZjQ4OTFiNGQtN2E3Yi00OTQ4LTg2NTYtNWZkY2Y0YmQ2N2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDEwMDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZDQxMDM4ZmE4NmNkYjNjYmU3ZDFhNzgyY2ZhNGYxMTUwZGRhNmVmYTljMGE5ODZiZmJkNmJjZDgxOTE5N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z6T_hL9Xbz4M0VgdF02KmC1FuJqy6sJ6jdJoDsdMiJI) ![图像](https://private-user-images.githubusercontent.com/59501159/360856171-83dcc6af-024c-479e-9327-0af574f62350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDc4ODQsIm5iZiI6MTczNTIwNzU4NCwicGF0aCI6Ii81OTUwMTE1OS8zNjA4NTYxNzEtODNkY2M2YWYtMDI0Yy00NzllLTkzMjctMGFmNTc0ZjYyMzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDEwMDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOTEwNWQ4N2Q5MDNhMmUyMmY4ODE0YjU4MTYyZDMxMzFhZTQ4NDVkN2Q2YWRmNDcxNTNkODJkNmE4NTA0NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9EvlkSkmJwndp_igQepLajEL9hFB5fh7-RccmWUVz0M)

你这些问题找到新的模型了吗？

**Comment by ZhengPeng7** [comment]
Github repo release和google drive 上都有的呀, 全全的.
