### ISSUE TITLE
Onnx accuracy

### ISSUE THREAD

**Issue by jtsanborn1** [ZhengPeng7/BiRefNet#59]
Hi, First of all thanks for developing this and making them available for the community. 

I've downloaded the onnx models and i found they are not as accurate as the pytorch ones, why is that? the pytorch models gives more details

Is it something to do with the code? operators? 

TIA

**Comment by ZhengPeng7** [comment]
Yeah, as I mentioned in the ONNX conversion part, the predicted results are a bit different. It might be caused by the deform_conv2d conversion from torch to ONNX.
But in my cases, the difference is limited and tolerable. Could you provide the cases that you think are worse?

**Comment by jtsanborn1** [comment]
Thanks for your response! 

Please see this 
<img width="628" alt="Screen Shot 2024-08-20 at 9 53 42 AM" src="https://github.com/user-attachments/assets/973f4c3b-072d-4683-93c5-4f152876c005">
<img width="674" alt="Screen Shot 2024-08-20 at 9 53 54 AM" src="https://github.com/user-attachments/assets/ebc79978-e7e2-4c92-bac0-abc20a34932c">

There's quite a difference!

**Comment by ZhengPeng7** [comment]
The first ones are generated by the ONNX-converted files. They seem to be some quantized results...

**Comment by ZhengPeng7** [comment]
Hi, @jtsanborn1 , could you send me the original images above? I want to take a deeper look into the problem here.

**Comment by jtsanborn1** [comment]
Hi @ZhengPeng7 
Thanks for taking the time to help with this! 

Here are the original images> https://we.tl/t-1iitatt2Za

**Comment by ZhengPeng7** [comment]
Great! I've downloaded them and will take some time to look at the problem.

**Comment by ZhengPeng7** [comment]
Hi, @jtsanborn1 , I tested the onnx (BiRefNet_T) and the results seem to be good (the difference is very limited). Here is the [temporary colab](https://colab.research.google.com/drive/1wBQrTU6eTTRmNLq0WgmsGIUdfuP3rymD?usp=sharing) for you to run and check the difference. And also, the screenshot of those two results of the second example image:


<img width="1173" alt="截屏2024-08-25 22 08 46" src="https://github.com/user-attachments/assets/789cf422-1f87-4692-9ba1-85e004140d9b">

**Comment by jtsanborn1** [comment]
Hey t his looks really good! Is this done with a new conversion? I want to try this locally, can you share the exact onnx model file you used for this test?

**Comment by ZhengPeng7** [comment]
It's the same model, which is downloaded from my release. You can run the colab I provided above to have a try and do a comparison.

**Comment by ZhengPeng7** [comment]
What code did you use? Can you try my colab above? Maybe something is wrong with your processing codes (I guess it is about the threshold).
