### ISSUE TITLE
dont work on folder , dont work on image sets and if i download it is original image -> i mus t push my right mousebuttun to save it

### ISSUE THREAD

**Issue by kalle07** [ZhengPeng7/BiRefNet#61]
dont work on folder , dont work on image set and if i download it is original image imus t push my right mousebuttun to save it

**Comment by ZhengPeng7** [comment]
You mean you want to do the inference on a batch of images more easily?
Actually, I've made up the inference and evaluation of image sets in the colab, as given in the head of README.
Tell me if you can work with it. If not, tell me the problem and I'll try to further simplify it.

**Comment by kalle07** [comment]
i dont use colab ;)

i the old build in version in a1111  ... may you can copy past or take a look

**Comment by ZhengPeng7** [comment]
What do you mean by "a1111"?

**Comment by kalle07** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by ZhengPeng7** [comment]
Sorry, I'm not familiar with the SD-WebUI... And I cannot find BiRefNet codes integrated there.

**Comment by kalle07** [comment]
its same gui like webforge

![grafik](https://github.com/user-attachments/assets/67039c2a-4b21-4fad-89d4-d23f3aefcc28)

but i dont know were its called in any py ???

**Comment by ZhengPeng7** [comment]
Hey, there seems to be U^2-Net instead of BiRefNet.
And also, this is a question about the GUI. Maybe you'd better ask for help in their repos since I'm not an expert on it.

**Comment by ZhengPeng7** [comment]
Besides, if you want to do the inference with BiRefNet on a batch of images (let's say, in a folder), you can easily do it on our colab demo for inference only: https://colab.research.google.com/drive/14Dqg7oeBkFEtchaHLNpig2BcdkZEogba, which is attached in the head of README.

**Comment by ZhengPeng7** [comment]
Hey, @kalle07, I wrote it to [README](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#third-party-creations) days ago but forgot to reply to you that a piece of good news is here: you can find a great extension (by @dimitribarbot) that integrates BiRefNet into WebUI, which may meet your need: https://github.com/dimitribarbot/sd-webui-birefnet.

The author also made a [PR](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/pull/47) in the official repo of [AUTOMATIC1111/stable-diffusion-webui-rembg](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg).

**Comment by yo1nkers** [comment]
Been using this extension for a couple days now, and I'm addicted.
@kalle07 You'll find this more than suits your needs. Revolutionary for the popularity of BiRefNet
