### ISSUE TITLE
各数据集上分别使用的最佳backbone

### ISSUE THREAD

**Issue by whyandbecause** [ZhengPeng7/BiRefNet#63]
您好，这个工作对我们特别有启发意义。但是我有一个小问题，各数据集所使用的最好的backbone是一样的吗？如果不一样的话，各自对应哪个backbone？谢谢！

**Comment by ZhengPeng7** [comment]
Hi, 感谢支持! 一般来讲, 都是使用同一个backbone, 不然也不太公平, 且比较的计算代价太大了. 我们之前默认用SwinL做的, 后来就一直维持不变. 最后为了补齐论文里的efficiency-performance的trade-off, 我就还是分别用常见的那些backbone, 在DIS5K的benchmark上都训了一遍. 结果发现SwinB其实和SwinL差别不大.
所以, 如果你的计算资源充足, 那就直接用SwinL就好了. 如果不是很充足, 或者想要网络更轻量一点, 用SwinB大概率也能维持一个差不多的水准.

**Comment by ZhengPeng7** [comment]
有后续问题欢迎re-open issue, 继续留言.
