### ISSUE TITLE
Heavy and Portrait models

### ISSUE THREAD

**Issue by okaris** [ZhengPeng7/BiRefNet#65]
Thank you for this amazing model! It's lightweight, fast and accurate. I was also impressed by the quality of the heavy and portrait models hosted on fal. Are these available in pytorch/safetensors format for using with the diffusers library?

**Comment by ZhengPeng7** [comment]
Hi, @okaris @luke14free, glad to see your interest! The weights used in https://fal.ai/models/birefnet are the latest ones. I've been keeping in contact with guys there, so you can easily use weights there.

If you also want to download the weights, you can check the [model-zoo](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#model-zoo) section in README for all weights in .pth. For weights in safetensors, check my HF page for all related weights, for example, the one for general use: https://huggingface.co/ZhengPeng7/BiRefNet.

Currently, I don't know how to embed BiRefNet into `diffuser`. Could you help me with it or give me some clues?

**Comment by okaris** [comment]
Thanks for the quick rreply @ZhengPeng7 

sorry I meant Transformers not Diffusers. We want to br able to run the models within a pipeline and not as a seperate API call. 

I have tried every model in the zoo but couldn’t get the same results as fal with any of them. Is the heavy model in fal something that doesn’t wxist in the zoo?

**Comment by ZhengPeng7** [comment]
Hi, I've contacted them. They used a legacy version for general use, which didn't have training on portrait seg data.
I've made a HF model repo for it: https://huggingface.co/ZhengPeng7/BiRefNet-legacy, and added the choice of that weights in my [HF spaces demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo). You can have a check now :)

**Comment by okaris** [comment]
That's awesome, thank you very much!

**Comment by ZhengPeng7** [comment]
You're welcome. There was a bug when loading the legacy version weights in my HF demo. Now it's fixed, and the results of it should be exactly the same as those of the results of FAL's general (heavy) model.
