### ISSUE TITLE
The difference between “General” model in HF and github？

### ISSUE THREAD

**Issue by sandy-ssdut** [ZhengPeng7/BiRefNet#69]
Hey, I test a image with HF (general) model, and github (general) model, but the output is different. Seems that the HF model make better result. 

<img width="983" alt="image" src="https://github.com/user-attachments/assets/5672c945-5f1c-4081-b4f6-eddcdbddffcb">

<img width="476" alt="image" src="https://github.com/user-attachments/assets/793cb49f-7ba8-42b6-bf77-e10f7cda56e9">

<img width="571" alt="image" src="https://github.com/user-attachments/assets/7d185583-d0e3-4131-b03b-dbb963511acb">
<img width="821" alt="image" src="https://github.com/user-attachments/assets/663d12e3-5802-4195-9732-6a87e6d11d27">

Is there difference between General model in HF and github?

**Comment by ZhengPeng7** [comment]
They should be precisely the same. You can use the inference colab in README to try on different weights.

**Comment by sandy-ssdut** [comment]
I tried this colab  [Colab demo for single image inference](https://colab.research.google.com/drive/14Dqg7oeBkFEtchaHLNpig2BcdkZEogba)  and HF with same image.  But the output is different.

**Comment by sandy-ssdut** [comment]
And the output of general-legacy model is different in HF and FAL.

**Comment by ZhengPeng7** [comment]
Hi, of course, https://huggingface.co/ZhengPeng7/BiRefNet is different from https://huggingface.co/ZhengPeng7/BiRefNet-legacy (general-legacy).
+ 1). https://huggingface.co/ZhengPeng7/BiRefNet: the latest one
+ 2). https://huggingface.co/ZhengPeng7/BiRefNet-legacy: the old version.
+ 3). FAL model (general heavy): same as 2).

**Comment by ZhengPeng7** [comment]
Here are the three results (I cropped a part of that from FAL since the image is rendered with a white background after loading the results image):

1).
> Pay attention to the choice of weights in the screenshot
<img width="1570" alt="截屏2024-08-26 18 05 31" src="https://github.com/user-attachments/assets/56454700-383e-47ad-8571-082f90c2db0a">

2).
<img width="1589" alt="截屏2024-08-26 18 09 28" src="https://github.com/user-attachments/assets/771a9b8c-fc91-4970-87bf-47bba6d29aef">

3).
<img width="1147" alt="截屏2024-08-26 18 07 43" src="https://github.com/user-attachments/assets/04a841bc-19a4-48ec-8283-46f15f42c833">

**Comment by sandy-ssdut** [comment]
In this image， the output is different.

2) HF general-legacy
<img width="1465" alt="image" src="https://github.com/user-attachments/assets/56dc8802-aa21-4221-b21f-8b2cf5aadf9c">

3) FAL general heavy
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/d7bccd02-7a8d-4e63-ac4c-7f0e3dad6e97">

**Comment by sandy-ssdut** [comment]
In this image, the output of HF - general & colab - general is different.

HF general:
<img width="911" alt="image" src="https://github.com/user-attachments/assets/512240e6-7445-465a-8588-3f3a7bb98b95">

colab in readme:
<img width="682" alt="image" src="https://github.com/user-attachments/assets/976a7673-272a-47ad-9485-aae19bf69e08">
<img width="829" alt="image" src="https://github.com/user-attachments/assets/df2e928b-38bf-4346-a63b-24aee32a766f">

**Comment by ZhengPeng7** [comment]
Great, glad to find out why they differ :) 1024x1024 is the suggested resolution, which is also the value during training.

**Comment by ZhengPeng7** [comment]
Thanks for your issue! I suddenly realized why there are sometimes OOM errors in the log of my HF space demo. I should have set the resolution as the original one when users give it nothing. I'm closing this issue now, but feel free to re-open it again if you have any continual problems.

> Oh, I find the difference between HF demo and colab.
> 
> In HF demo, if user do not input resolution, the resolution will be determined by the shape of input image. In colab, resolution is set as 1024x1024 for all images.
> 
> For non-square input image, like 800x600, the output mask is different when set model resolution as 1024x1024 and 800 // 32 * 32 x 600 // 32 * 32
