### ISSUE TITLE
Can't train smaller models, bb = 0, 1, 2

### ISSUE THREAD

**Issue by SolicTous** [ZhengPeng7/BiRefNet#70]
Trying set one of 'vgg16', 'vgg16bn', 'resnet50', changing self.bb to 0 or 1 or 2, but getting `RuntimeError: Given groups=1, weight of size [64, 3712, 3, 3], expected input[1, 1856, 128, 128] to have 3712 channels, but got 1856 channels instead` even in case of changing input from 1024 to 512 and etc.

Set to 3 or 6 works as normal.

**Comment by ZhengPeng7** [comment]
Hi, I'm sorry that only Swin and PVT are currently supported for the backbone ([ref](https://github.com/ZhengPeng7/BiRefNet/issues/19#issue-2262986664)). These channel numbers cannot be defined by ourselves, which is defined by the backbone networks, no matter if it's VGG16 or Swin Transformer.
