### ISSUE TITLE
Image Sequence Inference

### ISSUE THREAD

**Issue by jtsanborn1** [ZhengPeng7/BiRefNet#72]
Is there a way to run the inference on image sequence like a batch instead of single frame?

Thanks!

**Comment by ZhengPeng7** [comment]
Hi, I've upgraded the initial single image inference colab in README to the **multiple images inference** version, you can try that. All images in a folder you specify will be inferenced in a loop.

**Comment by jtsanborn1** [comment]
Cool, its working fine! Thank you!! What about running it locally?

**Comment by ZhengPeng7** [comment]
You can save the colab to your computer as a notebook and remove the `!xxx` commands. It won't cost you one minute. But if there is any problem, feel free to ask me again.

**Comment by ZhengPeng7** [comment]
Hi, I also found a HF spaces of BiRefNet which support online inference on a batch of images. You can have a try on it (it doesn't have GPU and could be a little slow): https://huggingface.co/spaces/NegiTurkey/Multi_Birefnetfor_Background_Removal

**Comment by ZhengPeng7** [comment]
I'll also add this function to my official HF space.

**Comment by ZhengPeng7** [comment]
You can now use [this notebook](https://github.com/ZhengPeng7/BiRefNet/blob/main/tutorials/BiRefNet_inference_video.ipynb) in tutorials for the inference on videos.
