### ISSUE TITLE
Smaller model for embedded into apps

### ISSUE THREAD

**Issue by ralphilius** [ZhengPeng7/BiRefNet#77]
Hello,

Thanks for this great model. I want to embed `onnx` file into my apps, so is there any way to make it even smaller? I'm thinking like sub 40-50MB would be adequate enough.

**Comment by ZhengPeng7** [comment]
Hi, We've provided BiRefNet with swin_v1_tiny as the backbone trained for general use, of which the params number is ~44.4M. You can find it in the model zoo or directly load it via https://huggingface.co/ZhengPeng7/BiRefNet_T.
The **ONNX** file can be found in the GitHub release or the "ONNX" folder in the Google Drive folder of BiRefNet.
