### ISSUE TITLE
Error when use .onnx on web

### ISSUE THREAD

**Issue by tidus2102** [ZhengPeng7/BiRefNet#78]
Hi, I tried to test .onnx on web (CPU) using [onnx-community/BiRefNet_T](https://huggingface.co/onnx-community/BiRefNet_T).
Here is index.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Background Removal</title>
</head>
<body>
<script type="module">
  import { AutoModel, AutoProcessor, RawImage } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers';

  // Load model and processor
  const model_id = 'onnx-community/BiRefNet_T';
  const model = await AutoModel.from_pretrained(model_id, { dtype: 'fp32' });
  const processor = await AutoProcessor.from_pretrained(model_id);

  // Load image from URL
  const url = 'https://images.pexels.com/photos/5965592/pexels-photo-5965592.jpeg?auto=compress&cs=tinysrgb&w=1024';
  const image = await RawImage.fromURL(url);

  // Pre-process image
  const { pixel_values } = await processor(image);

  // Predict alpha matte
  const { output_image } = await model({ input_image: pixel_values });
  console.log(output_image);
</script>
</body>
</html>
```

Check Chrome dev tools > Application tab > Cache storage, the .onnx file is loaded & cached without problem:
![Screenshot 2024-08-28 at 20 07 41](https://github.com/user-attachments/assets/be398fac-317e-4105-b01f-37b3e3ff5a58)

But I got error at predict code line:
```javascript
const { output_image } = await model({ input_image: pixel_values })
```

![hiLBrmNL_G8aENlwRHGGQ](https://github.com/user-attachments/assets/89739771-079a-4c97-98c4-d3d83e302a24)

I try the other input images, got the same issue.
Please help to check it. Thank you.

**Comment by ZhengPeng7** [comment]
Thanks for letting me know about this problem. I'm not familiar with the web app, but I will look into it tomorrow and reply to you then.

**Comment by ZhengPeng7** [comment]
Have you tried following the example codes in my [HF space demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo)? You can click the `Use via API` at the bottom of the page and follow the instructions there (with an uploaded image or a URL to the online image):
<img width="115" alt="截屏2024-08-29 14 06 01" src="https://github.com/user-attachments/assets/cf79f0c8-a463-4504-aa19-6b5652db0403">
![截屏2024-08-29 14 07 55](https://github.com/user-attachments/assets/0d35c0c6-5db3-47a1-81fb-8b4583043b41)

**Comment by tidus2102** [comment]
Thanks for your reply. I already tried your demo spaces and it works. I only ask about issue when using .onnx file on js (using [transformers.js](https://huggingface.co/docs/transformers.js/en/index)). I haven't tried BiRefNet .onnx on python but saw you and someone have tried it [here](https://github.com/ZhengPeng7/BiRefNet/issues/59).

About .onnx on js, I tested the [briaai/RMBG-1.4](https://huggingface.co/briaai/RMBG-1.4), it works without any issues. So I'm not sure if BiRefNet .onnx file got some issues. I haven't tried create .onnx file again from pytorch file on my local (I'm using Macbook M1).

**Comment by ZhengPeng7** [comment]
Please use the official ONNX files (you can download them from the GitHub release or GDrive folder given in README). I'm not saying their ONNX files are wrong, but I don't know whether there is any problem.

**Comment by ZhengPeng7** [comment]
Hi, Hung, I tried to learn about this problem. I also saw that you raised a discussion in the ONNX-community's HF repo. I really appreciate it, but I'm really not good at (even a noob) web deployment (things like transformers.js). Very sorry for that. If I'm not so busy with other work in recent days, I'll try to learn and solve it step by step.

Could you send me your demo projects, which I could build from zero, so I can test the error you encounter? Many thanks! If I solve it by myself, you'll get notified here. Finally, let me add a need-help badge to this issue to see if any other guy is good at it and do some help.

**Comment by tidus2102** [comment]
hi, sorry for the late reply, I tried to find out more about this issue after got your reply.

First, the .onnx file on [onnx-community/BiRefNet_T](https://huggingface.co/onnx-community/BiRefNet_T) is the same with your .onnx on github releases.

Second, here is my demo code: [https://codesandbox.io/p/sandbox/birefnet-onnx-5c7vv8](https://codesandbox.io/p/sandbox/birefnet-onnx-5c7vv8)

NOTE: 
- running BiRefNet_T model takes longer time than RMBG-1.4 (on my Macbook M1, it takes about 20 seconds then raise error) 
- when run (multiple times) the Chrome tab may consume very high RAM, it will crash if your machine doesn't have enough RAM, if it crashed just open the tab again
![Screenshot 2024-09-01 at 14 09 15](https://github.com/user-attachments/assets/61de545b-e51c-4d82-8020-2dea946b5fa4)

Demo run:
![Screenshot 2024-09-01 at 14 08 48](https://github.com/user-attachments/assets/a3c864a3-c41f-432d-9de1-61df9eef4fb9)
![Screenshot 2024-09-01 at 14 08 03](https://github.com/user-attachments/assets/a66cab19-6495-4517-9baf-f41d1bcbcacd)

Check Chrome dev tools > Console tab to see the model config (both models) after model loaded:
onnx-community/BiRefNet_T .onnx config:
```json
{
    "model_type": "swin",
    "is_encoder_decoder": false,
    "normalized_config": {
        "model_type": "swin",
        "is_encoder_decoder": false
    }
}
```

briaai/RMBG-1.4 .onnx config:
```json
{
    "model_type": "SegformerForSemanticSegmentation",
    "is_encoder_decoder": false,
    "_name_or_path": "briaai/RMBG-1.4",
    "architectures": [
        "BriaRMBG"
    ],
    "auto_map": {
        "AutoConfig": "MyConfig.RMBGConfig",
        "AutoModelForImageSegmentation": "briarmbg.BriaRMBG"
    },
    "custom_pipelines": {
        "image-segmentation": {
            "impl": "MyPipe.RMBGPipe",
            "pt": [
                "AutoModelForImageSegmentation"
            ],
            "tf": [],
            "type": "image"
        }
    },
    "in_ch": 3,
    "out_ch": 1,
    "torch_dtype": "float32",
    "transformers_version": "4.38.0.dev0",
    "normalized_config": {
        "model_type": "SegformerForSemanticSegmentation",
        "is_encoder_decoder": false
    }
}
```

Error when run predict with BiRefNet .onnx
![Screenshot 2024-09-01 at 14 04 03](https://github.com/user-attachments/assets/eb917bf9-0045-4910-928f-c6a59de1fe78)

Check Chrome dev tools > Application tab > Cache storage > transformers-cache for .onnx model files load from huggingface:
![Screenshot 2024-09-01 at 13 54 46](https://github.com/user-attachments/assets/a134e936-5ede-467a-9a21-8abf6e391934)

Third:
- I tried to create my own .onnx file (general lite weight) on google colab, I modified some of your demo code so my output .onnx different with your .onnx but still got the same error when use with js.
- I tried to use your .onnx & mine with python => both works, no problem.

Summary: the BiRefNet .onnx only got error with js, I see significant differences when log 2 models config. Hope this helps. Thank you.

**Comment by xenova** [comment]
Hi there 👋 The model (with the example code) runs fine in Node.js, so if I had to guess, it is an out of memory issue due to browser resource constraints. I think there are two fixes we can consider:
1. Export at a lower input shape (instead of 1024x1024)
2. Export with dynamic shapes

**Comment by ZhengPeng7** [comment]
Thanks for your kind explanation, @xenova !
BTW, the default and best resolution for most cases is 1024x1024, since that's the resolution used in training.
Hi, @tidus2102, does this solve your problem?

**Comment by tidus2102** [comment]
@xenova @ZhengPeng7 Thank for your support. How to export at a lower input shape (instead of 1024x1024)? Can you give me some sample code?

**Comment by xenova** [comment]
FYI - the ORT team is looking into this: https://github.com/microsoft/onnxruntime/issues/21968

**Comment by ZhengPeng7** [comment]
Hi, @xenova. Could you help me with another thing? I renamed the previous `BiRefNet_T` to `BiRefNet_lite` as https://huggingface.co/ZhengPeng7/BiRefNet_lite for users understand the meaning more easily. Could you also rename it in the transformers.js and https://huggingface.co/onnx-community/BiRefNet_T?
Many thanks!!

**Comment by xenova** [comment]
> Hi, @xenova. Could you help me with another thing? I renamed the previous `BiRefNet_T` to `BiRefNet_lite` as https://huggingface.co/ZhengPeng7/BiRefNet_lite for users understand the meaning more easily. Could you also rename it in the transformers.js and https://huggingface.co/onnx-community/BiRefNet_T?
> 
> Many thanks!!

Updated 👍 the new link is now: https://huggingface.co/onnx-community/BiRefNet_lite

**Comment by ZhengPeng7** [comment]
Hi, @tidus2102, if you still face some problems there, you can also try this great project to run BiRefNet-ONNX with JavaScript and node.js, made by @adha9990.

**Comment by tidus2102** [comment]
Hi @ZhengPeng7, please check this [comment](https://github.com/microsoft/onnxruntime/issues/21968#issuecomment-2349372743) to see if there is any solution for .onnx memory issue (on web). Thank you.

**Comment by ZhengPeng7** [comment]
Hi, @tidus2102. Thanks for letting me know about this problem. But I'm really not very familiar with web applications. But have you tried the [birefnet-onnx-sample](https://github.com/adha9990/birefnet-onnx-sample) I mentioned above? If you have specific problems there, I can try to contact the original author of it.

**Comment by tidus2102** [comment]
Hi @ZhengPeng7, I already tried [birefnet-onnx-sample](https://github.com/adha9990/birefnet-onnx-sample), .onnx on node works without any problem. I will keep follow up the issue on web on [microsoft/onnxruntime#21968](https://github.com/microsoft/onnxruntime/issues/21968). Thank you.

**Comment by ZhengPeng7** [comment]
Glad to see that! And thanks to @adha9990's nice work on that.
