### ISSUE TITLE
RuntimeError: Windows not yet supported for torch.compile

### ISSUE THREAD

**Issue by rendenzvous** [ZhengPeng7/BiRefNet#8]
May I ask if this project cannot run on windows? I have encountered this problem, RuntimeError: Windows not yet supported for torch.compile,
 indicates that windows does not currently support torch.compile
![20240327164818](https://github.com/ZhengPeng7/BiRefNet/assets/131849654/92e904ae-876c-4da8-a54a-0e016c8a24ab)

**Comment by ZhengPeng7** [comment]
Of course, you can run it on Windows. Just turn off the `compile` option in `config.py`. Without compilation, the training will be slower but can still run as expected.
Since I seldom run codes on Windows, plz respond to me if you encounter any other problems.

**Comment by rendenzvous** [comment]
thanks，but i encoutered other problems

**Comment by ZhengPeng7** [comment]
No worry, show me them.
