### ISSUE TITLE
one line code exception

### ISSUE THREAD

**Issue by coollofty** [ZhengPeng7/BiRefNet#82]
```
from transformers import AutoModelForImageSegmentation
birefnet = AutoModelForImageSegmentation.from_pretrained('ZhengPeng7/BiRefNet', trust_remote_code=True)
```

Exception raised:

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/ZhengPeng7/BiRefNet/resolve/main/adapter_config.json

There is indeed no file such as "adapter_config. json" in the specified path

**Comment by coollofty** [comment]
Resolved

**Comment by ZhengPeng7** [comment]
Hi, coollofty, sorry for bothering you. Could you tell me how did you solve it?

**Comment by coollofty** [comment]
> Hi, coollofty, sorry for bothering you. Could you tell me how did you solve it?

Online loading is not possible, but directly load the model locally after cloning it

**Comment by ZhengPeng7** [comment]
Got it, thanks!
