### ISSUE TITLE
怎么有些细节效果不如老版的580模型

### ISSUE THREAD

**Issue by lldacing** [ZhengPeng7/BiRefNet#85]
你好，新模型的效果整体效果对比老版本表现非常好，但有些图的细节不如老版本，我在comfyui上移植了一个插件支持新老版本做测试，下面是一个例子

新模型对第一张图片（变色龙）的效果表现非常好，对第二张图片的效果，细节不如原来的580模型（箭头所指的地方不干净）
![image](https://github.com/user-attachments/assets/e912043e-cf82-40b8-9599-3b28ad108632)

我测试了框选的这些模型，第二张图片都打不到580模型的效果
![image](https://github.com/user-attachments/assets/c3c3e7a5-be29-44e7-913f-8c77d801e7d8)

第二张测试原图及结果图
![20240905193322](https://github.com/user-attachments/assets/57e90fdf-f2c0-44e7-b0e5-72c3b4c01570)
580模型效果
![image](https://github.com/user-attachments/assets/1c6ed5fa-74e0-4f79-8a8d-2ea488085149)
新版效果
![image](https://github.com/user-attachments/assets/829cdc86-c1c4-4a04-9c35-2892161c92ee)

**Comment by ZhengPeng7** [comment]
Hi, 这个是一个取舍的问题. 之前那个ep_580是在`DIS5K`的训练集上训练得到的, [这个数据集](https://github.com/xuebinqin/DIS)的标注非常精细, 因此不错. General版本是在大量的数据集上训练的, 很多数据集的标注质量并非那么高, 因此通用型来说肯定是要更好的, 而且可以具有透明度. 但某些样本不如也是正常的, 比如你看Model Zoo里的比较, 在DIS-VD上的效果是不如只用DIS-TR训练的模型分数高的. 因为数据集之间也有gap.

之前也有些人确实是General之外的模型更适合他, [issue](https://github.com/ZhengPeng7/BiRefNet/issues/58#issuecomment-2306609608).

但在我的测试中, General在确定大致样本上是明显好很多的, 只用DIS5K训练的模型有可能在少部分样本的细节上好一些, 但coarse map的严重错误会显著多, 这个在实用场景是不能接受的. 所以, 我个人还是推荐默认就用General, 如果有精力可以根据自己样本的整体效果来选用其他的权重.

**Comment by lldacing** [comment]
> Hi, 这个是一个取舍的问题. 之前那个ep_580是在`DIS5K`的训练集上训练得到的, [这个数据集](https://github.com/xuebinqin/DIS)的标注非常精细, 因此不错. General版本是在大量的数据集上训练的, 很多数据集的标注质量并非那么高, 因此通用型来说肯定是要更好的, 而且可以具有透明度. 但某些样本不如也是正常的, 比如你看Model Zoo里的比较, 在DIS-VD上的效果是不如只用DIS-TR训练的模型分数高的. 因为数据集之间也有gap.
> 
> 之前也有些人确实是General之外的模型更适合他, [issue](https://github.com/ZhengPeng7/BiRefNet/issues/58#issuecomment-2306609608).
> 
> 但在我的测试中, General在确定大致样本上是明显好很多的, 只用DIS5K训练的模型有可能在少部分样本的细节上好一些, 但coarse map的严重错误会显著多, 这个在实用场景是不能接受的. 所以, 我个人还是推荐默认就用General, 如果有精力可以根据自己样本的整体效果来选用其他的权重.

感谢解答，我又测试了DIS-TR-TEs模型，确实可以达到同样效果，是我之前测试时疏忽了
