### ISSUE TITLE
Train model on local windows machine

### ISSUE THREAD

**Issue by hakantrkmn** [ZhengPeng7/BiRefNet#86]
can i really train this model with my custom dataset ? i looked at the documentatiton but i didnt understand. i have my own dataset which has 1k image and coco json annotations. i want to train it with my windows pc. it would be so good if someone tell me how should folder structure would be and extra things to do.

**Comment by ZhengPeng7** [comment]
Hi, coco JSON files are not needed. All you need is the `TASK_NAME/CUSTOM_DATASET/im` and `TASK_NAME/CUSTOM_DATASET/gt`, containing original images and the GT maps, respectively.

You can see the training on `DIS5K` as an example:
1. make a folder named `DIS5K`.
2. put datasets under the folder as `DIS5K/DIS-TR, DIS5K/DIS-VD, ...`.
3. make sure you have `im` and `gt` in each dataset (e.g., `DIS5K/DIS-TR/im, DIS5K/DIS-TR/gt`).
4. search all `"DIS5K" or 'DIS5K'` in the whole project (via vscode or GitHub) and adapt the corresponding values to your custom ones. For example, `DIS5K` -> `task_1`, `DIS-TR` -> `dataset_1`, `'DIS5K': ['DIS-TR', 'DIS-TR+DIS-TE1+DIS-TE2+DIS-TE3+DIS-TE4'][0]` -> `'task_1': '+'.join(['dataset_1', 'dataset_2'])`.
5. run `./train.sh` or `./train_test.sh` (if you have already had and correctly set the validation things).
