### ISSUE TITLE
why the result of mask obtaining the value "1" in the four corners of the image?

### ISSUE THREAD

**Issue by luoshuiyue** [ZhengPeng7/BiRefNet#87]
the result is :
![1a9bfdb756bb1d015bcf259443be86b](https://github.com/user-attachments/assets/b1235416-5801-4b41-88fd-c3e62be6265b)
but the four corners of the image obtaining value “1”：
<img width="953" alt="3eaa4aef37fc6c791d4cfe3e731f14a" src="https://github.com/user-attachments/assets/6f7c7783-7c27-41f1-a730-f41c581a0860">
<img width="971" alt="9344069808f07e8033d85d3201030e6" src="https://github.com/user-attachments/assets/9b4bc63b-7de2-4eb3-b85a-8a5286a2efc6">
<img width="971" alt="10c7441a99050a6215a8537d25e8271" src="https://github.com/user-attachments/assets/9f564a26-52a5-49ab-bb03-108817244e45">
<img width="971" alt="8282735c8fe98f3263fd29f81699084" src="https://github.com/user-attachments/assets/cb9627a7-92b3-4a35-8c7c-f6aac099332a">

How can I adjust the code so that these values are not generated?

**Comment by ZhengPeng7** [comment]
Wow, that's really weird! Thanks for letting me know about this phenomenon. I guess it may be caused by the sampling/resizing? You can take a look at the output tensors without resizing to the size of original images.
If you just simply want to remove these pixel values, you can easily set the pixel values of these four corners to 0 manually. Removing the contours with an area < 3 may also help, but is more time-consuming.

Also, I'll check if there is an issue of that with the labels of training data.

**Comment by luoshuiyue** [comment]
I test the ` pred_pil = pred_pil.resize(original_size)`. It seems not caused by `resize`. 
I still want to find the reason to correct instead of just changing to 0 in certain cases, because the four corner areas of the image can also be the foreground.

**Comment by ZhengPeng7** [comment]
Hi, @luoshuiyue, forgot to tell you that I also tested some images, but the corners do not have the non-zero predictions.

And I just finished the training on [BiRefNet_lite-2K](https://huggingface.co/ZhengPeng7/BiRefNet_lite-2K), where the higher resolution samples are selected and used for training in `2560x1440`. You can try it to see if it's better than the previous one (trained in `1024x1024` but not lite) with [my demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo), where I added the option of it today.

**Comment by luoshuiyue** [comment]
Thank you very much! I will try it.

**Comment by ZhengPeng7** [comment]
Since it's "BiRefNet_lite-2K", you need to set the backbone as `swin_v1_tiny`. Meanwhile, change the `task` in `config.py` to `General-2K` or manually set the `size` there as `(2560, 1440)`.
