### ISSUE TITLE
Inference Issue 

### ISSUE THREAD

**Issue by Kaustubh-cpu** [ZhengPeng7/BiRefNet#88]
@DengPingFan @ZhengPeng7 
When i am trying to run the inference command is it asking me for the Ground truth 

epoch_150.pth" --pred_root "/home/ml2/Desktop/Vscode/Biref/codes/dis/Biref/BiRefNet/demo_dataset/output" --testsets "/home/ml2/Desktop/Vscode/Biref/codes/dis/Biref/BiRefNet/demo_dataset/input"
Testing with models in ckpt/BiRefNet-portrait-epoch_150.pth
>>>> Testset: /home/ml2/Desktop/Vscode/Biref/codes/dis/Biref/BiRefNet/demo_dataset/input...
Not exists: /home/ml2/Desktop/Vscode/Biref/codes/dis/Biref/BiRefNet/demo_dataset/input/gt/0801_pm_wm4884.JPEG
Path diff: {'0801_pm_wm4884'}
Traceback (most recent call last):
  File "/home/ml2/Desktop/Vscode/Biref/codes/dis/Biref/BiRefNet/inference.py", line 106, in <module>
    main(args)
  File "/home/ml2/Desktop/Vscode/Biref/codes/dis/Biref/BiRefNet/inference.py", line 62, in main
    dataset=MyData(testset, image_size=config.size, is_train=False),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ml2/Desktop/Vscode/Biref/codes/dis/Biref/BiRefNet/dataset.py", line 79, in __init__
    raise ValueError(f"There are different numbers of images ({len(self.label_paths)}) and labels ({len(self.image_paths)})")
ValueError: There are different numbers of images (0) and labels (1)

**Comment by ZhengPeng7** [comment]
Run the inference with
1. the notebook in tutorials,
2. colab,
3. HF demo.

**Comment by Kaustubh-cpu** [comment]
Thankyou for your response  @ZhengPeng7  

what is the use of inference.py .is it not configured for the inference at present

**Comment by ZhengPeng7** [comment]
`inference.py` can also be used for inference. However, the difference is that this file is used for the inference in the three steps of experiments, i.e., `train-inference-evaluation`, to conduct experiments for better methods. Therefore, many settings are fixed to make it a faster and easier process on that, while it could not be 100% compatible with the practical use of inference.

**Comment by Kaustubh-cpu** [comment]
@ZhengPeng7  
Also can you please give some suggestion as i want to finetune pretrained on my dataset also experinment with different backbone
