### ISSUE TITLE
the training stalls

### ISSUE THREAD

**Issue by rendenzvous** [ZhengPeng7/BiRefNet#9]
the training stalls, always in the first iteration of the first epoch，my gpu is 16G，my dataset just 39 pictures。
![Uploading 2222.png…]()

**Comment by ZhengPeng7** [comment]
You picture was not uploaded successfully...

**Comment by rendenzvous** [comment]
![2222](https://github.com/ZhengPeng7/BiRefNet/assets/131849654/6f2aeac0-7ac9-4da7-9508-e4dc75a1f82a)  here is

**Comment by ZhengPeng7** [comment]
But, what is the problem here?... It seems no trouble in training as the logs are being printed.

**Comment by rendenzvous** [comment]
> You picture was not uploaded successfully...

it don't move. don't have any reaction. don't move to the next Interation and the next epoch

**Comment by ZhengPeng7** [comment]
Really? you can decrease the resolution of input for training, e.g., 512x512, to test if it's just slow. I remember Windows has some mechanism to use CPU memory as a supplement for GPU memory, which though causes much much delay. BTW, as I mentioned in README, 36.5G GPU memory is needed to use my default setting.

**Comment by rendenzvous** [comment]
> Really? you can decrease the resolution of input for training, e.g., 512x512, to test if it's just slow. I remember Windows has some mechanism to use CPU memory as a supplement for GPU memory, which though causes much much delay. BTW, as I mentioned in README, 36.5G GPU memory is needed to use my default setting.  

thank you so much ,it has been sloved,best wishes to you!

**Comment by ZhengPeng7** [comment]
Glad to hear that. Good luck to you too :)
