### ISSUE TITLE
Assistance needed with Fine-Tuning Model on Custom Dataset

### ISSUE THREAD

**Issue by kparikh-tenup** [ZhengPeng7/BiRefNet#90]
Hi @ZhengPeng7,

Appreciate your excellent work on this model.

I tried the HF demo with the General weights to remove the background from the car's interior image, but it was unable to do so. In this case, the background refers to all areas visible outside the car, as seen through the windshield and side windows.

**Original Image (with highlighted areas for removal):**

![sample-image-1](https://github.com/user-attachments/assets/1499f73d-8e37-4966-b766-7d1dc8479894)

**BiRefNet Prediction:**

![sample-image-1-pred](https://github.com/user-attachments/assets/435dddd0-7446-443d-9080-f33a4e63e4bf)

We plan to address this by fine-tuning or training the model. We have created a custom dataset of 3000 car interior images (original and mask) but have a few questions,

1. With a dataset of 3000 samples, should we train from scratch using `swim_tiny` bb or fine-tune with existing `BiRefNet-general-epoch_224.pth` weight?
2. For fine-tuning, how many epochs should we start with if we are considering the `BiRefNet-general-epoch_224.pth` weights?
3. Could you please verify the steps below for fine-tuning with the `BiRefNet-general-epoch_224.pth` weights?
   a. Download the latest version of `BiRefNet-general-epoch_224.pth` from the stuff.
   b. Move it to `ckpt/general/epoch_224.pth`.
   c. Edit `train.sh` and update the `--resume` parameter from `--resume xx/xx-epoch_244.pth` to `--resume ckpt/general/epoch_224.pth`.
   d. Execute the command to run on single GPU `./train.sh general 0 0`

Thanks,
Kaushal

**Comment by ZhengPeng7** [comment]
Hi, @kparikh-tenup. It's easy to do, and let me reply to your questions one by one:
1. Backbone: if your GPU cards can hold the GPU memory cost of training, concerning the batch size > 2 and reasonable resolution, try to use a larger backbone. 3000 samples is already enough for training from scratch / fine-tuning.
2. It depends. As my suggestion, you can fine-tune it for about 50 epochs to see if the model does what you want correctly. If yes, train it longer (let's say 100~150 epochs).
3. Yeah, the steps should be correct. But remember, you use the `resume` option instead of adding the "loading weights process" after model initialization; you need to check the definition of epoch number. The resuming training should start from 224 -- if you want to resume training another `N` epochs, you should set the epoch number to `224+N`.

Tell me if you have any problem now or later.

**Comment by kparikh-tenup** [comment]
Hi @ZhengPeng7, thank you for your response. Could you please assist me with a few more questions?

1. Our custom dataset images are 4032 x 3024 or 3680 x 2760. Should I update the ‘self.size’ in config.py when fine-tuning with BiRefNet-general-epoch_224.pth or use the default 1024 x 1024?"

2. During inference, our image resolution will be same i.e. 4032 x 3024 or 3680 x 2760. Should I resize the image to the resolution set in ‘self.size’ in config.py before making predictions?

**Comment by ZhengPeng7** [comment]
Sure, you are welcome :)
1. Currently, I suggest you use 1024x1024 first since your GPU might not be able to deal with the `4032 x 3024` data, which is too large. Besides, your cases seem to have fewer regions with fine details, which requires HR images.
2. The resolution of inference should be the same as used in training. In some cases, you may find HR resolution inference may generate better results, but generally, we always recommend the exact resolution).

**Comment by kparikh-tenup** [comment]
When fine-tuning with BiRefNet-general-epoch_224.pth, I wanted to confirm a few things related to `config.py`.

1. Do I need to update `self.task` from `DISK5` to `General`? Is that correct?
2. For the 'General' option under `self.training_set`, should I configure `datasets_all` or just only our custom dataset?

**Comment by ZhengPeng7** [comment]
1. It depends on the name of the folder in which you put the data.
2. Specify the "training_set" manually if you have some other data but don't want to use them. Otherwise, it's okay.

**Comment by kparikh-tenup** [comment]
> 1. It depends on the name of the folder in which you put the data.
> 2. Specify the "training_set" manually if you have some other data but don't want to use them. Otherwise, it's okay.

Okay, but in a nutshell, for fine-tuning, we only need to use our custom dataset and not the dataset used to train the 'General' task from scratch, i.e., ['DIS-TR', 'DIS-TR+DIS-TE1+DIS-TE2+DIS-TE3+DIS-TE4, more....'].

Is that correct?

**Comment by ZhengPeng7** [comment]
Yeah, I know. You should make sure that there is only your custom dataset in the `General` folder, if you want to set the task to `General`.

**Comment by dankrasno** [comment]
@ZhengPeng7 are there more details on training? I ran the same steps for training mentioned [above](https://github.com/ZhengPeng7/BiRefNet/issues/90#issue-2548356602), and ran `./train.sh general 0 0`, but I keep running into errors. 

Latest is 
```
(birefnet) ubuntu@ip-xxxx:~/BiRefNet$ ./train.sh general 0 0 
Training started at Mon Sep 30 08:38:52 UTC 2024
Single-GPU mode received...
2024-09-30 08:38:54,372 INFO datasets: load_all=False, compile=True.
2024-09-30 08:38:54,372 INFO Other hyperparameters:
2024-09-30 08:38:54,372 INFO Namespace(resume='ckpt/general/epoch_224.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/general', testsets='NO', dist=False)
batch size: 4
750 batches of train dataloader DIS-TR have been created.
Traceback (most recent call last):
  File "/home/ubuntu/BiRefNet/train.py", line 337, in <module>
    main()
  File "/home/ubuntu/BiRefNet/train.py", line 321, in main
    model_opt_lrsch=init_models_optimizers(args.epochs, to_be_distributed)
  File "/home/ubuntu/BiRefNet/train.py", line 100, in init_models_optimizers
    model = BiRefNet(bb_pretrained=True)
  File "/home/ubuntu/BiRefNet/models/birefnet.py", line 28, in __init__
    self.bb = build_backbone(self.config.bb, pretrained=bb_pretrained)
  File "/home/ubuntu/BiRefNet/models/backbones/build_backbone.py", line 25, in build_backbone
    bb = load_weights(bb, bb_name)
  File "/home/ubuntu/BiRefNet/models/backbones/build_backbone.py", line 40, in load_weights
    state_dict = {k: v if v.size() == model_dict[k].size() else model_dict[k] for k, v in save_model[sub_item].items() if k in model_dict.keys()}
KeyError: None
Training finished at Mon Sep 30 08:38:56 UTC 2024
```
and I'm not sure what to do? What is the simplest full process to train model (on any dataset included in this repo?)?

**Comment by ZhengPeng7** [comment]
Hi, @dankrasno. Are you sure you are using the correct backbone weights and the corresponding backbone choice in the `config.py`?
