### ISSUE TITLE
Any Installation guildline?

### ISSUE THREAD

**Issue by SnowTung999** [ZhengPeng7/BiRefNet#91]
Any Installation guildline?
I dont know how to install in comfyui and cant auotmatic installation in comfyui manager.
May be crash other nodes. dznodes

**Comment by ZhengPeng7** [comment]
I don't hold the ComfyUI nodes with BiRefNet. But it seems not difficult to follow: https://github.com/MoonHugo/ComfyUI-BiRefNet-Hugo/blob/main/README_EN.md#installation. You can leave issues there if you have any problems.
