### ISSUE TITLE
最近代码移除了bb_index输入并且默认为6，在我机器上lite模型推理出错

### ISSUE THREAD

**Issue by zmwv823** [ZhengPeng7/BiRefNet#92]
前两天升级了torch等一系列库，发现开始爆显存了。以前刚好卡在3.9gb，现在涨到4.3gb，刚好看到修复了type问题https://github.com/ZhengPeng7/BiRefNet/commit/2ff88ae4b1371fc766914c8e1f030ae1293319c8 。测试了下半精度推理，显存占用直接砍半。
但是发现lite模型推理会失败，lite和标准模型相比少了参数量，所以直接使用移除了bb_index输入的代码 https://github.com/ZhengPeng7/BiRefNet/blob/main/config.py 会报错，不知是否是我机器上的个例。
自己加回bb_index输入就没问题了。
```
  File "D:\AI\7860-HivisionIDPhotos\hivision\creator\human_matting.py", line 487, in get_birefnet_transformers_birefnet_lite
    Transformers_BIREFNET_V1_LITE_SESS.load_state_dict(BIREFNET_state_dict)
  File "D:\AI\ComfyUI_windows_portable\py311\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BiRefNet:
        Missing key(s) in state_dict: "bb.layers.2.blocks.6.norm1.weight", 
```

**Comment by ZhengPeng7** [comment]
不懂你的意思, 你给的PR链接是task的单引号双引号bug, 和显存没关呀.
半精度推理效果会有所不同.
更关键的是, 你这个代码是"HivisionIDPhotos"里的。。。你起码得给个BiRefNet的错误, 不然我怎么提供帮助?

**Comment by zmwv823** [comment]
> 不懂你的意思, 你给的PR链接是task的单引号双引号bug, 和显存没关呀. 半精度推理效果会有所不同. 更关键的是, 你这个代码是"HivisionIDPhotos"里的。。。你起码得给个BiRefNet的错误, 不然我怎么提供帮助?

抱歉，前面几句是废话。问题我自己解决了(参照以前代码把bb_index加了回去)，只是好奇bb_index参数是否还有必要。
我把这个模型集成到HivisionIDPhotos流程里抠图，所以报错会从它这里出来，使用的huggingface的readme里面的推理代码(Use codes from GitHub + weights from local space: Only use the weights and codes both locally.)。
```
import torch
from utils import check_state_dict
birefnet = BiRefNet(bb_pretrained=False)
state_dict = torch.load(PATH_TO_WEIGHT, map_location='cpu')
state_dict = check_state_dict(state_dict)
birefnet.load_state_dict(state_dict)
```
使用lite模型推理时报错。
## 错误信息：Missing key(s) in state_dict: "bb.layers.2.blocks.6.norm1.weight"
lite模型bb_index貌似是3，最近更新的代码里bb_index固定为6:
- https://github.com/ZhengPeng7/BiRefNet/blob/main/models/birefnet.py 第24行：`def __init__(self, bb_pretrained=True):` ，没有了bb_index输入。
- https://github.com/ZhengPeng7/BiRefNet/blob/main/config.py 第71-77行：
```
self.bb = [
            'vgg16', 'vgg16bn', 'resnet50',         # 0, 1, 2
            'swin_v1_t', 'swin_v1_s',               # 3, 4
            'swin_v1_b', 'swin_v1_l',               # 5-bs9, 6-bs4
            'pvt_v2_b0', 'pvt_v2_b1',               # 7, 8
            'pvt_v2_b2', 'pvt_v2_b5',               # 9-bs10, 10-bs5
        ][6] # 以前代码这里是bb_index值输入，现在固定为6。
```
在ComfyUI里，如果使用lite模型，会加一个判定：
bb_index = 3 if 'lite' in model_name else 6
self.BiRefNet = BiRefNet(bb_pretrained=False, bb_index=bb_index)

**Comment by ZhengPeng7** [comment]
确实, 是可以这么做. 我以后应该也会保持lite版本的model名称里包含`lite`的.
