### ISSUE TITLE
General question 

### ISSUE THREAD

**Issue by antithing** [ZhengPeng7/BiRefNet#94]
Hi, and thanks for making this code available!

General question, how are the segments chosen by the model? 

My use case is human segmentation with a complex background.

Which of your models would be most suitable?
Would this work directly, or would passing a box be better?

Thanks!

**Comment by ZhengPeng7** [comment]
The portrait or general should be the best ones. You can use my HF demo to make a comparison: https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo.

If the scene is very complex and the human might not be the most dominant/salient subject, passing a box may be better to eliminate the distractors.
