### ISSUE TITLE
Finetunning Issue 

### ISSUE THREAD

**Issue by Kaustubh-cpu** [ZhengPeng7/BiRefNet#96]
Hello @ZhengPeng7 

I am getting issue in Finetunning and Results
1. when i start the traininig its working well but when i give the path of checkpoint with the --resume parameter ....For finetunning ...process suddenly stopped 
(15 batches of train dataloader DIS-TR have been created.
Found correct weights in the "model" item of loaded state_dict.
2024-10-01 09:45:58,086 INFO => loading checkpoint 'ckpt/BiRefNet-DIS-bb_swin_v1_tiny-epoch_575.pth'
2024-10-01 09:45:58,475 INFO Optimizer details:
2024-10-01 09:45:58,476 INFO AdamW (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    initial_lr: 5e-05
    lr: 5e-05
    maximize: False
    weight_decay: 0.01
)
2024-10-01 09:45:58,476 INFO Scheduler details:
2024-10-01 09:45:58,476 INFO <torch.optim.lr_scheduler.MultiStepLR object at 0x7a3d6708ff40>)

**Comment by Kaustubh-cpu** [comment]
@ZhengPeng7 
When i trained model from stratch on small sample of data i am, getting the results :-----/home/ml2/Desktop/Vscode/Biref/codes/dis/Biref/BiRefNet/predictions/0801_pm_wm4884.jpg

**Comment by Kaustubh-cpu** [comment]
@ZhengPeng7 

When i trained the model from the scratch on small sample of data  I am getting total white image in the result 
![0801_pm_wm4884](https://github.com/user-attachments/assets/4f22662d-94fb-4314-ac50-65209044dc6d)

**Comment by Kaustubh-cpu** [comment]
@ZhengPeng7 

If you are there ....i need suggestion for this please if you can help ,me

**Comment by ZhengPeng7** [comment]
As I said, if you want to use the `resume`, the new epoch set in fine-tuning needs to be the epochs you want to fine-tune `+` the epoch number of the resumed checkpoint.

**Comment by Kaustubh-cpu** [comment]
@ZhengPeng7 
Thankyou for you help ..........i resolved that but there is one more error 

(return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.)
