### ISSUE TITLE
How to find the edge better？

### ISSUE THREAD

**Issue by duxuan11** [ZhengPeng7/BiRefNet#97]
For the first image I used birefnet to get the good result, now I want to get the edge of the mask, but I find that cv2.findContours does not get good results. How to find the edge better？
![image](https://github.com/user-attachments/assets/37a0c9e7-140f-4a9e-be79-40c7bf9f1615)
![image](https://github.com/user-attachments/assets/4a325f2d-f57b-4aa2-878f-1856a94da149)

contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

**Comment by ZhengPeng7** [comment]
Personally, I suggest you use two methods to remove the noise contours:
1. morphology operation.
2. remove contours with smaller areas.

**Comment by duxuan11** [comment]
Thank you for your advice, I was wondering if there was a way to outline the target edges more accurately (morphological manipulation is necessary) and how to filter out the blurred pixels.

**Comment by ZhengPeng7** [comment]
Sure. If you have similar data used for training, model will definitely get more familiar with those cases and perform better there.

**Comment by duxuan11** [comment]
I'm sorry to bother you, I understand my needs, I need a high-precision segmentation algorithm, so I want to convert the cutout algorithm to a segmentation algorithm, alpha can only take 0 or 1. So, do you have any good suggestions?

**Comment by ZhengPeng7** [comment]
How did you use BiRefNet to obtain your results above?
If you directly use it, there might be some gaps between the training and your data, such as resolution, data domain, object class, etc.
So, I suggest you do some fine-tuning (for <200 samples) or training from scratch (if you have >200 samples) according to the settings of your original (cell?) data.

**Comment by duxuan11** [comment]
I directly used it to obtain the cell segmentation mask, and found a few improvement on the edge by reducing blur radius(This parameter is used to perform blur fusion to estimate foreground and background images). 
I think train it on my dataset, and adjust the value of predicted_alpha_array during inference will be useful.

**Comment by ZhengPeng7** [comment]
Oh, you mean the post-processing of foreground-object-estimation? If it's a segmentation task instead of matting, you can feel free to remove it. It has obvious improvement on the transparent regions in matting but not very much in segmentation.

**Comment by duxuan11** [comment]
Thank you for your advice, which has been of great help to me.
